site_name: "mikeplus"

theme: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false # change this if you prefer to be able to show the source code inside the docs
          heading_level: 2
          docstring_style: "numpy" # default is google