<Symbologies>
  <symbology_file_type>
    <item>
      <key>type</key>
      <value type="System.Int32">1</value>
    </item>
  </symbology_file_type>
  <symbology>
    <item>
      <key>symbology_1</key>
      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
        <item>
          <key>layer_name</key>
          <value type="System.String">layera10d411b2e1941bfa6fbb8be08b64823</value>
        </item>
        <item>
          <key>catogary</key>
          <value type="System.Int32">12</value>
        </item>
        <item>
          <key>other_info</key>
          <value type="System.Int32">0</value>
        </item>
        <item>
          <key>layer_prop</key>
          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
            <item>
              <key>type</key>
              <value type="System.Int32">12</value>
            </item>
            <item>
              <key>title</key>
              <value type="System.String">Default</value>
            </item>
            <item>
              <key>visible</key>
              <value type="System.Boolean">True</value>
            </item>
            <item>
              <key>is_active</key>
              <value type="System.Boolean">True</value>
            </item>
            <item>
              <key>symbology_name</key>
              <value type="System.String">a08cfa1a-8a61-4f42-a5d9-2a42c9580466</value>
            </item>
            <item>
              <key>feature_type</key>
              <value type="System.Int32">1</value>
            </item>
            <item>
              <key>result_layer_base</key>
              <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                <item>
                  <key>style_type</key>
                  <value type="System.Int32">0</value>
                </item>
              </value>
            </item>
            <item>
              <key>symbol_props</key>
              <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                <item>
                  <key>symbol_options</key>
                  <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                    <item>
                      <key>show_symbol</key>
                      <value type="System.Boolean">True</value>
                    </item>
                    <item>
                      <key>expression</key>
                      <value type="System.Nullable" />
                    </item>
                    <item>
                      <key>symbology_type</key>
                      <value type="System.Int32">4</value>
                    </item>
                    <item>
                      <key>symbol_scope</key>
                      <value type="System.Int32">0</value>
                    </item>
                  </value>
                </item>
                <item>
                  <key>default_settings</key>
                  <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                    <item>
                      <key>default_no</key>
                      <value type="System.Int32">4</value>
                    </item>
                    <item>
                      <key>default_setting_1</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">1</value>
                        </item>
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16744448</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">9</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>default_setting_2</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">2</value>
                        </item>
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16744448</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">9</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>default_setting_3</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16744448</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">9</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>default_setting_4</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">3</value>
                        </item>
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16744448</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">9</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>color_range</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>colorramp</key>
                          <value type="System.String">-8388480:0;-16776961:20;-16734554:40;-16711936:60;-256:80;-65536:100</value>
                        </item>
                        <item>
                          <key>invert</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>size_range</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>size_from</key>
                          <value type="System.Single">2</value>
                        </item>
                        <item>
                          <key>size_to</key>
                          <value type="System.Single">10</value>
                        </item>
                      </value>
                    </item>
                  </value>
                </item>
                <item>
                  <key>category_settings</key>
                  <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                    <item>
                      <key>symbol_field</key>
                      <value type="System.String">TS Value</value>
                    </item>
                    <item>
                      <key>symbol_field_typecode</key>
                      <value type="System.Int32">14</value>
                    </item>
                    <item>
                      <key>classify_no</key>
                      <value type="System.Int32">10</value>
                    </item>
                    <item>
                      <key>category_setting_1</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-1</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">-10</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: -10-0</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_2</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-128</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">-12566464</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">0</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 0-15</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_3</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16772363</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">15</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 15-25</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_4</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16748861</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">25</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 25-30</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_5</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16729727</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">30</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 30-40</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_6</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-16717020</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">40</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 40-50</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_7</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-11206912</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">50</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 50-60</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_8</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-32768</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">7</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">60</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 60-70</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_9</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-4177920</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">70</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: 70-80</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                    <item>
                      <key>category_setting_10</key>
                      <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                        <item>
                          <key>feature_style</key>
                          <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                            <item>
                              <key>feature_type</key>
                              <value type="System.Int32">1</value>
                            </item>
                            <item>
                              <key>fill_color</key>
                              <value type="System.Drawing.Color">-65536</value>
                            </item>
                            <item>
                              <key>outline_color</key>
                              <value type="System.Drawing.Color">16777215</value>
                            </item>
                            <item>
                              <key>point_size</key>
                              <value type="System.Single">8</value>
                            </item>
                            <item>
                              <key>point_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>outline_thickness</key>
                              <value type="System.Single">1</value>
                            </item>
                            <item>
                              <key>layer_transparency</key>
                              <value type="System.Int32">20</value>
                            </item>
                            <item>
                              <key>symbol_style</key>
                              <value type="System.Int32">0</value>
                            </item>
                            <item>
                              <key>bitmap</key>
                              <value type="System.String">
                              </value>
                            </item>
                          </value>
                        </item>
                        <item>
                          <key>symbology_type</key>
                          <value type="System.Int32">4</value>
                        </item>
                        <item>
                          <key>break_value</key>
                          <value type="System.String">80</value>
                        </item>
                        <item>
                          <key>description</key>
                          <value type="System.String">TS Value: above 80</value>
                        </item>
                        <item>
                          <key>is_others_style</key>
                          <value type="System.Boolean">False</value>
                        </item>
                      </value>
                    </item>
                  </value>
                </item>
                <item>
                  <key>labeling</key>
                  <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                    <item>
                      <key>showlabel</key>
                      <value type="System.Boolean">False</value>
                    </item>
                    <item>
                      <key>labelfield</key>
                      <value type="System.String">TS Value</value>
                    </item>
                    <item>
                      <key>fontsize</key>
                      <value type="System.Int32">10</value>
                    </item>
                    <item>
                      <key>decimal_place</key>
                      <value type="System.Int32">3</value>
                    </item>
                    <item>
                      <key>fontstyle</key>
                      <value type="System.Int32">0</value>
                    </item>
                    <item>
                      <key>fontcolor</key>
                      <value type="System.Drawing.Color">-16777216</value>
                    </item>
                  </value>
                </item>
                <item>
                  <key>adv_labeling</key>
                  <value type="System.Collections.Generic.Dictionary`2[System.String,System.Object]">
                    <item>
                      <key>gridsize</key>
                      <value type="System.Int32">50</value>
                    </item>
                    <item>
                      <key>position</key>
                      <value type="System.Int32">0</value>
                    </item>
                    <item>
                      <key>label_duplicate_rule</key>
                      <value type="System.Int32">0</value>
                    </item>
                    <item>
                      <key>overlapping_rule</key>
                      <value type="System.Int32">0</value>
                    </item>
                    <item>
                      <key>textline_segment_ratio</key>
                      <value type="System.Double">1</value>
                    </item>
                    <item>
                      <key>x_offset</key>
                      <value type="System.Single">5</value>
                    </item>
                    <item>
                      <key>y_offset</key>
                      <value type="System.Single">10</value>
                    </item>
                  </value>
                </item>
              </value>
            </item>
          </value>
        </item>
      </value>
    </item>
  </symbology>
</Symbologies>