"""The Import Tool from MIKE+."""
import os.path
from DHI.Amelia.Tools.ImportTool.ImportEngine import FunctionHelper
from DHI.Amelia.Tools.ImportTool.ImportEngine import ImportToolBase


class ImportTool:
    """The Import Tool from MIKE+.

    Parameters
    ----------
    configFile: A xml configuration file. This file can be generated by MIKE+ application.
    dataTables: DataTableContainer, it can be empty. If it is empty, it will create a new empty database.

    Examples
    --------
    >>>data_access = DataTableAccess(muppOrSqlite)
    >>>data_access.open_database()
    >>>import_tool = ImportTool("../tests/testdata/import/config.xml", data_access.datatables)
    >>>import_tool.run()
    >>>data_access.close_database()

    """

    def __init__(self, configFile, dataTables=None):
        """Initialize the ImportTool with the given configuration file and DataTables.

        Parameters
        ----------
        configFile : str
            A xml configuration file. This file can be generated by MIKE+ application.
        dataTables : DataTableContainer, optional
            It can be empty. If it is empty, it will create a new empty database.

        """
        self._configFile = os.path.abspath(configFile)
        self._dataTables = dataTables

    def run(self):
        """Run the import tool."""
        import_engine = ImportToolBase(self._dataTables)
        import_engine.Load(self._configFile)
        FunctionHelper.ChangeFilePathInConfigToAbsolute(
            import_engine.JobConfigSectionsDic, self._configFile
        )
        import_engine.OnTableDataProcessing += self._on_table_data_processing
        import_engine.Run()

    def _on_table_data_processing(self, source, args):
        print(args.TileInfo)
