from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class m2d_BoundaryTableColumns(BaseColumns):
    """Column names for m2d_Boundary (2D boundary conditions)."""
    MUID = "MUID"
    """ID"""
    ApplyNo = "ApplyNo"
    """Apply"""
    BndTypeNo = "BndTypeNo"
    """Type"""
    TimeTypeNo = "TimeTypeNo"
    """HD type"""
    ConstValue = "ConstValue"
    """Constant value"""
    ConstStartupNo = "ConstStartupNo"
    """Gradual start up, constant"""
    ConstStartValue = "ConstStartValue"
    """From, constant"""
    ConstTimeInterval = "ConstTimeInterval"
    """Time, constant [sec]"""
    VarStartupNo = "VarStartupNo"
    """Gradual start up, varying"""
    VarStartValue = "VarStartValue"
    """From, varying"""
    VarTimeInterval = "VarTimeInterval"
    """Time, varying [sec]"""
    WaterFilePath = "WaterFilePath"
<<<<<<< HEAD
    """File name"""
    WaterItemNo = "WaterItemNo"
    """WaterItemNo"""
    WaterItemName = "WaterItemName"
    """Item"""
=======
    WaterItemName = "WaterItemName"
    WaterItemNo = "WaterItemNo"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    ConstInitVelApplyNo = "ConstInitVelApplyNo"
    """Const apply initial velocity"""
    Discharge = "Discharge"
    """Discharge [m^3/s]"""
    UVelocity = "UVelocity"
    """u-velocity [m/s]"""
    VVelocity = "VVelocity"
    """v-velocity [m/s]"""
    VarInitVelApplyNo = "VarInitVelApplyNo"
    """Varying apply initial velocity"""
    SourceFilePath = "SourceFilePath"
    """File name"""
    SrcDisItemName = "SrcDisItemName"
<<<<<<< HEAD
    """Discharge item"""
    SrcUVelItemName = "SrcUVelItemName"
    """u-velocity item"""
    SrcVVelItemName = "SrcVVelItemName"
    """v-velocity item"""
=======
    SrcDisItemNo = "SrcDisItemNo"
    SrcUVelItemName = "SrcUVelItemName"
    SrcUVelItemNo = "SrcUVelItemNo"
    SrcVVelItemName = "SrcVVelItemName"
    SrcVVelItemNo = "SrcVVelItemNo"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    QhDisFilePath = "QhDisFilePath"
    """Q/h file"""
    QhDisItemNo = "QhDisItemNo"
    """QhDisItemNo"""
    QhDisItemName = "QhDisItemName"
    """Discharge item"""
    QhVelocityFilePath = "QhVelocityFilePath"
<<<<<<< HEAD
    """Velocity file"""
    QhUVelItemNo = "QhUVelItemNo"
    """QhUVelItemNo"""
    QhUVelItemName = "QhUVelItemName"
    """u-velocity item"""
    QhVVelItemNo = "QhVVelItemNo"
    """QhVVelItemNo"""
    QhVVelItemName = "QhVVelItemName"
    """v-velocity item"""
=======
    QhUVelItemName = "QhUVelItemName"
    QhUVelItemNo = "QhUVelItemNo"
    QhVVelItemName = "QhVVelItemName"
    QhVVelItemNo = "QhVVelItemNo"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    QHStartupNo = "QHStartupNo"
    """Gradual start up"""
    QHStartValue = "QHStartValue"
    """From [m]"""
    QHTimeInterval = "QHTimeInterval"
    """Time [sec]"""
    VelDefTypeNo = "VelDefTypeNo"
    """Velocity definition type"""
    InterpolationTypeNo = "InterpolationTypeNo"
    """Interpolation type in time"""
    SpatialOrderNo = "SpatialOrderNo"
    """Spatial order along boundary"""
    SourceTypeNo = "SourceTypeNo"
    """Source type"""
    Source1X = "Source1X"
    """X [m]"""
    Source1Y = "Source1Y"
    """Y [m]"""
    Source2X = "Source2X"
    """X [m]"""
    Source2Y = "Source2Y"
    """Y [m]"""
    Description = "Description"
<<<<<<< HEAD
    """Description"""
    BndGeomLine = "BndGeomLine"
    """BndGeomLine"""
    SrcDisItemNo = "SrcDisItemNo"
    """SrcDisItemNo"""
    SrcUVelItemNo = "SrcUVelItemNo"
    """SrcUVelItemNo"""
    SrcVVelItemNo = "SrcVVelItemNo"
    """SrcVVelItemNo"""
=======
    EventID = "EventID"
    BndGeomLine = "BndGeomLine"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)

class m2d_BoundaryTable(BaseGeometryTable):
    """Table for m2d_Boundary (2D boundary conditions)."""
    
    @property
    def columns(self) -> m2d_BoundaryTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = m2d_BoundaryTableColumns(self)
        return self._columns