from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class m2d_CouplingTableColumns(BaseColumns):
    """Column names for m2d_Coupling (1D-2D couplings)."""
    MUID = "MUID"
    """ID"""
    TypeNo = "TypeNo"
    """Type"""
    CoupleModelNo = "CoupleModelNo"
<<<<<<< HEAD
    """Couple to"""
    ApplyNo = "ApplyNo"
    """Apply"""
=======
    Enabled = "Enabled"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    ItemID = "ItemID"
    """Coupled ID"""
    RecalculationCoordinateNo = "RecalculationCoordinateNo"
    """Allow for recalculation"""
    Uschainage = "Uschainage"
    """From upstream chainage [m]"""
    Dschainage = "Dschainage"
    """To downstream chainage [m]"""
    SideNo = "SideNo"
    """Side"""
    SquareWidth = "SquareWidth"
    """Square width [m]"""
    RiverEndNo = "RiverEndNo"
    """River end"""
    FlowDistributionNo = "FlowDistributionNo"
    """Flow distribution"""
    RiverStruID = "RiverStruID"
    """Structure ID"""
    NodeID = "NodeID"
    """Node ID"""
    RiverDistance = "RiverDistance"
    """Length and distance from river [m]"""
    DeltaDepth = "DeltaDepth"
    """Delta depth for dampening [mm]"""
    Smoothing = "Smoothing"
    """Smoothing factor"""
    WeirTypeNo = "WeirTypeNo"
    """Weir type"""
    WeirCoef = "WeirCoef"
    """Weir coefficient"""
    CrestSourceNo = "CrestSourceNo"
    """Crest source"""
    CrestTable = "CrestTable"
    """Table"""
    FilePath = "FilePath"
    """File"""
    FileItemName = "FileItemName"
    """Item"""
    MaxQcheckNo = "MaxQcheckNo"
    """Apply max. Q"""
    MaxQvalue = "MaxQvalue"
    """Max. Q value [m^3/s]"""
    FlowMethodNo = "FlowMethodNo"
    """Method"""
    DischCoef = "DischCoef"
    """Discharge coefficient"""
    InletArea = "InletArea"
    """Inlet area [m^2]"""
    CrestWidth = "CrestWidth"
    """Crest width [m]"""
    Coefficient = "Coefficient"
    """Coefficient"""
    Exponent = "Exponent"
    """Exponent"""
    Freeboard = "Freeboard"
    """Freeboard [m]"""
    DQRelationID = "DQRelationID"
    """DQ relation ID"""

class m2d_CouplingTable(BaseGeometryTable):
    """Table for m2d_Coupling (1D-2D couplings)."""
    
    @property
    def columns(self) -> m2d_CouplingTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = m2d_CouplingTableColumns(self)
        return self._columns