from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class m2d_StructureCulvertTableColumns(BaseColumns):
    """Column names for m2d_StructureCulvert (2D culverts)."""
    MUID = "MUID"
    """ID"""
    ApplyNo = "ApplyNo"
    """Apply"""
    CulvertType = "CulvertType"
    """Culvert type"""
    GeomTypeNo = "GeomTypeNo"
    """Geometry type"""
    Width = "Width"
    """Width [m]"""
    Height = "Height"
    """Height [m]"""
    Diameter = "Diameter"
    """Diameter [m]"""
    NumberCulverts = "NumberCulverts"
    """Number of culverts"""
    USLevel = "USLevel"
    """Upstream invert [m]"""
    DSLevel = "DSLevel"
    """Downstream invert [m]"""
    Length = "Length"
    """Length [m]"""
    Manning = "Manning"
    """Manning (M) [m^(1/3)/s]"""
    DampDepth = "DampDepth"
    """Dampening delta depth [m]"""
    NonReturn = "NonReturn"
    """Non return flap"""
    FlowDistrib = "FlowDistrib"
    """Flow distribution"""
    SectionType = "SectionType"
    """Section type"""
    Momentum = "Momentum"
    """Momentum"""
    R2Lin = "R2Lin"
    """LI, R-L"""
    R2Lout = "R2Lout"
    """LO, R-L"""
    R2Lbend = "R2Lbend"
    """LB, R-L"""
    L2Rin = "L2Rin"
    """LI, L-R"""
    L2Rout = "L2Rout"
    """LO, L-R"""
    L2Rbend = "L2Rbend"
    """LB, L-R"""
    R2LCalibration = "R2LCalibration"
    """CF,R-L"""
    L2RCalibration = "L2RCalibration"
    """CF, L-R"""
    DataSource = "DataSource"
    """Data source"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""

class m2d_StructureCulvertTable(BaseGeometryTable):
    """Table for m2d_StructureCulvert (2D culverts)."""
    
    @property
    def columns(self) -> m2d_StructureCulvertTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = m2d_StructureCulvertTableColumns(self)
        return self._columns