from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mrm_STAdvFractionTableColumns(BaseColumns):
    """Column names for mrm_STAdvFraction (Sediment fractions)."""
    MUID = "MUID"
    """ID"""
    SedTypeNo = "SedTypeNo"
    """Sediment type"""
    Porosity = "Porosity"
    """Porosity of deposits [()]"""
    RelDensity = "RelDensity"
    """Relative density [()]"""
    Shields = "Shields"
    """Critical Shields parameter [()]"""
    FallDefNo = "FallDefNo"
    """Fall velocity mode"""
    FallVal = "FallVal"
    """Fall velocity value [m/s]"""
    DefaultSize = "DefaultSize"
    """Default grain size [mm]"""
    IncludeTypeNo = "IncludeTypeNo"
    """Include"""
    BedModelNo = "BedModelNo"
    """Bed load transport model"""
    BedFactor = "BedFactor"
    """Bed load factor [()]"""
    BedD90d30 = "BedD90d30"
    """d90/d30 [()]"""
    BedAngle = "BedAngle"
    """Angle of repose [deg]"""
    BedSlopeNo = "BedSlopeNo"
    """Slope dependency"""
    BedShieldsNo = "BedShieldsNo"
    """Shields stress"""
    Beda1 = "Beda1"
    """a1 [()]"""
    Beda2 = "Beda2"
    """a2 [()]"""
    Beda3 = "Beda3"
    """a3 [()]"""
    Beda4 = "Beda4"
    """a4 [()]"""
    Beda5 = "Beda5"
    """a5 [()]"""
    Beda6 = "Beda6"
    """a6 [()]"""
    Beda7 = "Beda7"
    """a7 [()]"""
    Beda8 = "Beda8"
    """a8 [()]"""
    SusModelNo = "SusModelNo"
    """Suspended load transport model"""
    SusFactor = "SusFactor"
    """Suspended load factor [()]"""
    SusD90d30 = "SusD90d30"
    """d90/d30 [()]"""
    SusAngle = "SusAngle"
    """Angle of repose [deg]"""
    SusSlopeNo = "SusSlopeNo"
    """Slope dependency"""
    SusShieldsNo = "SusShieldsNo"
    """Shields stress"""
    Susa1 = "Susa1"
    """a1 [()]"""
    Susa2 = "Susa2"
    """a2 [()]"""
    Susa3 = "Susa3"
    """a3 [()]"""
    Susa4 = "Susa4"
    """a4 [()]"""
    Susa5 = "Susa5"
    """a5 [()]"""
    Susa6 = "Susa6"
    """a6 [()]"""
    Susa7 = "Susa7"
    """a7 [()]"""
    Susa8 = "Susa8"
    """a8 [()]"""
    CohExp = "CohExp"
    """Exponent [()]"""
    CohErShear = "CohErShear"
    """Erosion shear stress limit [N/m^2]"""
    CohErCoef = "CohErCoef"
    """Erosion coefficient [g/m^2/s]"""
    CohDepShear = "CohDepShear"
    """Deposition shear stress limit [N/m^2]"""

class mrm_STAdvFractionTable(BaseTable):
    """Table for mrm_STAdvFraction (Sediment fractions)."""
    
    @property
    def columns(self) -> mrm_STAdvFractionTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_STAdvFractionTableColumns(self)
        return self._columns