from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mrm_BridgeOpeningTableColumns(BaseColumns):
    """Column names for mrm_BridgeOpening (mrm_BridgeOpening)."""
    MUID = "MUID"
    RiverBridgeID = "RiverBridgeID"
    Sqn = "Sqn"
    Method = "Method"
    AsymmetryChk = "AsymmetryChk"
    OpeningTypeNo = "OpeningTypeNo"
    OpeningTypeRNo = "OpeningTypeRNo"
    IncludePirNo = "IncludePirNo"
    PirWWBlock = "PirWWBlock"
    PirUseCustomNo = "PirUseCustomNo"
    PirCustomTable = "PirCustomTable"
    PileCustomTable1L = "PileCustomTable1L"
    PileCustomTable2L = "PileCustomTable2L"
    PirTypeNo = "PirTypeNo"
    IncludeSknNo = "IncludeSknNo"
    SknAngle = "SknAngle"
    SknUseCustomNo = "SknUseCustomNo"
    SknCustomTable = "SknCustomTable"
    IncludeEctrNo = "IncludeEctrNo"
    EctrUseCustomNo = "EctrUseCustomNo"
    EctrCustomTable = "EctrCustomTable"
    IncludeSpdNo = "IncludeSpdNo"
    SpdLength = "SpdLength"
    SpdLengthR = "SpdLengthR"
    SpdTypeNo = "SpdTypeNo"
    SpdTypeRNo = "SpdTypeRNo"
    SpdAngle = "SpdAngle"
    SpdAngleR = "SpdAngleR"
    SpdOffset = "SpdOffset"
    SpdOffsetR = "SpdOffsetR"
    SpdUseCustom = "SpdUseCustom"
    SpdUseCustomR = "SpdUseCustomR"
    SpdCustomTable1 = "SpdCustomTable1"
    SpdCustomTableR1 = "SpdCustomTableR1"
    SpdCustomTable2 = "SpdCustomTable2"
    SpdCustomTableR2 = "SpdCustomTableR2"
    RoughTypeNo = "RoughTypeNo"
    RoughValue = "RoughValue"
    RadioType = "RadioType"
    WaterwayLength = "WaterwayLength"
    WaterwayLengthR = "WaterwayLengthR"
    LevelOfLength = "LevelOfLength"
    LevelOfLengthR = "LevelOfLengthR"
    ContractionLoss = "ContractionLoss"
    ExpansionLoss = "ExpansionLoss"
    OpeningWidth = "OpeningWidth"
    ArchesNum = "ArchesNum"
    LevelBottom = "LevelBottom"
    LevelTop = "LevelTop"
    Radius = "Radius"
    UseCustomBaseNo = "UseCustomBaseNo"
    UseCustomBaseRNo = "UseCustomBaseRNo"
    CustomTableBase = "CustomTableBase"
    CustomTableBaseR = "CustomTableBaseR"
    UseCustomEntranNo = "UseCustomEntranNo"
    UseCustomEntranRNo = "UseCustomEntranRNo"
    CustomTableEntran = "CustomTableEntran"
    CustomTableEntranR = "CustomTableEntranR"
    EntranTypeNo = "EntranTypeNo"
    EntranTypeRNo = "EntranTypeRNo"
    EntranRadius = "EntranRadius"
    EntranRadiusR = "EntranRadiusR"
    EntranWidth = "EntranWidth"
    EntranWidthR = "EntranWidthR"
    EntranAngle = "EntranAngle"
    EntranAngleR = "EntranAngleR"
    EmbankSlope = "EmbankSlope"
    EmbankSlopeR = "EmbankSlopeR"
    UseCustromFroudeNo = "UseCustromFroudeNo"
    UseCustromFroudeRNo = "UseCustromFroudeRNo"
    CustromTableFroude = "CustromTableFroude"
    CustromTableFroudeR = "CustromTableFroudeR"
    UseCustromDepthNo = "UseCustromDepthNo"
    UseCustromDepthRNo = "UseCustromDepthRNo"
    CustromTableDepth = "CustromTableDepth"
    CustromTableDepthR = "CustromTableDepthR"
    UseCustromAbutNo = "UseCustromAbutNo"
    UseCustromAbutRNo = "UseCustromAbutRNo"
    CustromTableAbut = "CustromTableAbut"
    CustromTableAbutR = "CustromTableAbutR"
    UseCustromWWNo = "UseCustromWWNo"
    UseCustromWWRNo = "UseCustromWWRNo"
    CustromTableWW = "CustromTableWW"
    CustromTableWWR = "CustromTableWWR"
    WWAngle = "WWAngle"
    WWAngleR = "WWAngleR"
    TypeBaseNo = "TypeBaseNo"
    UseCustromVelNo = "UseCustromVelNo"
    CustromTableVel = "CustromTableVel"
    SubmergenceTypeNo = "SubmergenceTypeNo"
    SubMgcMethodNo = "SubMgcMethodNo"
    SubMgcDischargeCoef = "SubMgcDischargeCoef"
    SubMgcUseCustomTableNo = "SubMgcUseCustomTableNo"
    SubMgcCustomTable = "SubMgcCustomTable"
    SubMgcContraction = "SubMgcContraction"
    SubMgcExpansion = "SubMgcExpansion"
    SubMgcSoffitLevel = "SubMgcSoffitLevel"
    SubMgcCulvertID = "SubMgcCulvertID"
    OflMethodNo = "OflMethodNo"
    OflSurfaceNo = "OflSurfaceNo"
    OflUseCustomTableNo = "OflUseCustomTableNo"
    OflDischargeCoef1 = "OflDischargeCoef1"
    OflDischargeCoef2 = "OflDischargeCoef2"
    SubMgcFactor = "SubMgcFactor"
    OflLength = "OflLength"
    OflDeckLevel = "OflDeckLevel"
    OflWeirID = "OflWeirID"
    DatumUpCrs = "DatumUpCrs"
    UseCustromCrsUpNo = "UseCustromCrsUpNo"
    FromSUp = "FromSUp"
    ToSUp = "ToSUp"
    TableCrsUpID = "TableCrsUpID"
    DownCrsTypeNo = "DownCrsTypeNo"
    DownCrsSlope = "DownCrsSlope"
    DatumDownCrs = "DatumDownCrs"
    UseCustromCrsDownNo = "UseCustromCrsDownNo"
    FromSDown = "FromSDown"
    ToSDown = "ToSDown"
    TableCrsDownID = "TableCrsDownID"
    OffsetUSSection = "OffsetUSSection"
    OffsetDSSection = "OffsetDSSection"
    OffsetSub = "OffsetSub"
    OffsetOver = "OffsetOver"

class mrm_BridgeOpeningTable(BaseTable):
    """Table for mrm_BridgeOpening (mrm_BridgeOpening)."""
    
    @property
    def columns(self) -> mrm_BridgeOpeningTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_BridgeOpeningTableColumns(self)
        return self._columns