from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mrm_GateTableColumns(BaseColumns):
    """Column names for mrm_Gate (Gates)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    RiverID = "RiverID"
    """River ID"""
    Chainage = "Chainage"
    """Chainage [m]"""
    TypeNo = "TypeNo"
    """Gate type"""
    GateNo = "GateNo"
    """Number of gates"""
    Width = "Width"
    """Gate width [m]"""
    MaxLevel = "MaxLevel"
    """Max. gate level [m]"""
    SillLevel = "SillLevel"
    """Sill level [m]"""
    Height = "Height"
    """Gate height [m]"""
    Trunnion = "Trunnion"
    """Trunnion [m]"""
    Radius = "Radius"
    """Radius [m]"""
    HorizOffset = "HorizOffset"
    """Horizontal offset from marker 2 [m]"""
    MaxSpeed = "MaxSpeed"
    """Max. speed [m/s]"""
    InitialLevel = "InitialLevel"
    """Initial gate level [m]"""
    ApplyFactorNo = "ApplyFactorNo"
    """Apply flow factor"""
    FactorValue = "FactorValue"
    """Flow factor [()]"""
    PosInflow = "PosInflow"
    """Positive inflow"""
    PosOutflow = "PosOutflow"
    """Positive outflow"""
    PosFreeflow = "PosFreeflow"
    """Positive free overflow"""
    NegInflow = "NegInflow"
    """Negative inflow"""
    NegOutflow = "NegOutflow"
    """Negative outflow"""
    NegFreeflow = "NegFreeflow"
    """Negative free overflow"""
    ContracCoef = "ContracCoef"
    """Contraction coef."""
    HeadLossCmTypeNo = "HeadLossCmTypeNo"
    """Computational method"""
    RadialFactor = "RadialFactor"
    """Underflow factor"""
    RadialCoef = "RadialCoef"
    """Weir coefficient"""
    RadialExp = "RadialExp"
    """Weir exponent"""
    RadialTranBottom = "RadialTranBottom"
    """Transition bottom [m]"""
    RadialTranDepth = "RadialTranDepth"
    """Transition depth [m]"""
    Sluice_a_ContSub = "Sluice_a_ContSub"
    """Controlled submerged flow coef. a"""
    Sluice_a_ContFree = "Sluice_a_ContFree"
    """Controlled free flow coef. a"""
    Sluice_a_UncSub = "Sluice_a_UncSub"
    """Uncontrolled submerged flow coef. a"""
    Sluice_a_UncFree = "Sluice_a_UncFree"
    """Uncontrolled free flow coef. a"""
    Sluice_b_ContSub = "Sluice_b_ContSub"
    """Controlled submerged flow exp. b"""
    Sluice_b_ContFree = "Sluice_b_ContFree"
    """Controlled free flow exp. b"""
    Sluice_b_UncSub = "Sluice_b_UncSub"
    """Uncontrolled submerged flow exp. b"""
    Sluice_High_ContSub = "Sluice_High_ContSub"
    """Controlled submerged flow high limit"""
    Sluice_High_ContFree = "Sluice_High_ContFree"
    """Controlled free flow high limit"""
    Sluice_High_UncSub = "Sluice_High_UncSub"
    """Uncontrolled submerged flow high limit"""
    Sluice_Low_ContSub = "Sluice_Low_ContSub"
    """Controlled submerged flow low limit"""
    Sluice_Low_ContFree = "Sluice_Low_ContFree"
    """Controlled free flow low limit"""
    Sluice_Low_UncSub = "Sluice_Low_UncSub"
    """Uncontrolled submerged flow low limit"""
    DataSource = "DataSource"
    """Data source"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""

class mrm_GateTable(BaseGeometryTable):
    """Table for mrm_Gate (Gates)."""
    
    @property
    def columns(self) -> mrm_GateTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_GateTableColumns(self)
        return self._columns