from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mrm_SHECouplingsTableColumns(BaseColumns):
    """Column names for mrm_SHECouplings (Groundwater couplings)."""
    MUID = "MUID"
    """ID"""
    ApplyNo = "ApplyNo"
    """Apply"""
    TypeNo = "TypeNo"
    """Type"""
    RiverID = "RiverID"
    """River ID"""
    FromChainage = "FromChainage"
    """From lowest chainage [m]"""
    ToChainage = "ToChainage"
    """To highest chainage [m]"""
    WeirCoef = "WeirCoef"
    """Weir coefficient"""
    WeirExpCoeff = "WeirExpCoeff"
    """Weir exponent"""
    MinHeight = "MinHeight"
    """Min. upstream height above bank for full weir width [m]"""
    OverbankSpillNo = "OverbankSpillNo"
    """Allow overbank spilling from river to overland domain"""
    MinFlowArea = "MinFlowArea"
    """Min. flow area for overbank spilling [m^2]"""
    ConductanceNo = "ConductanceNo"
    """Conductance"""
    LeakageCoef = "LeakageCoef"
    """Leakage coefficient [/s]"""
    LineResExcNo = "LineResExcNo"
    """Linear reservoir exchange"""
    FloodAreaNo = "FloodAreaNo"
    """Flood area option"""
    FloodCode = "FloodCode"
    """Flood code"""
    BedTopoNo = "BedTopoNo"
    """Bed topography"""
    BedLeakageNo = "BedLeakageNo"
    """Bed leakage"""
    NodeID = "NodeID"
    """Node ID"""
    LinkID = "LinkID"
    """Pipe ID"""
    CoupleToOverlandFlowNo = "CoupleToOverlandFlowNo"
    """Couple to overland flow"""
    ExchangeCoeff = "ExchangeCoeff"
    """Weir coefficient"""
    ExchangeExponent = "ExchangeExponent"
    """Weir exponent [()]"""
    CoupleToDrainageNo = "CoupleToDrainageNo"
    """Couple to overland drainage"""
    GridCode = "GridCode"
    """Overland drainage grid code"""
    CoupleToSaturatedZoneNo = "CoupleToSaturatedZoneNo"
    """Couple to saturated zone"""
    ExchangeTypeNo = "ExchangeTypeNo"
    """Conductance"""
    GroutingCoeff = "GroutingCoeff"
    """Grouting coefficient [m/s]"""
    GroutingThickness = "GroutingThickness"
    """Grouting thickness [m]"""
    CoupleToSaturatedZoneDrainageNo = "CoupleToSaturatedZoneDrainageNo"
    """Couple to saturated zone drainage"""
    NetworkGridCode = "NetworkGridCode"
    """Saturated zone drainage grid code"""

class mrm_SHECouplingsTable(BaseGeometryTable):
    """Table for mrm_SHECouplings (Groundwater couplings)."""
    
    @property
    def columns(self) -> mrm_SHECouplingsTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_SHECouplingsTableColumns(self)
        return self._columns