from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mrm_DambreakTableColumns(BaseColumns):
    """Column names for mrm_Dambreak (Dambreak)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    RiverID = "RiverID"
    """River ID"""
    Chainage = "Chainage"
    """Chainage [m]"""
    BreachFormulATypeNo = "BreachFormulATypeNo"
    """Breach formula"""
    FailureModeTypeNo = "FailureModeTypeNo"
    """Failure mode"""
    CrestLevel = "CrestLevel"
    """Creast level before failure [m]"""
    CrestLength = "CrestLength"
    """Creast length before failure [m]"""
    FailureMomentTypeNo = "FailureMomentTypeNo"
    """Failure moment type"""
    FailureMomentHours = "FailureMomentHours"
    """Failure moment hours after start [h]"""
    ActiveDateTime = "ActiveDateTime"
    """Active date time"""
    WaterLevel = "WaterLevel"
    """ReservoirWL [m]"""
    PosInflow = "PosInflow"
    """Positive Inflow"""
    PosOutflow = "PosOutflow"
    """Positive Outflow"""
    PosFreeOverflow = "PosFreeOverflow"
    """Positive free overflow"""
    NegInflow = "NegInflow"
    """Negative Inflow"""
    NegOutflow = "NegOutflow"
    """Negative Outflow"""
    NegFreeOverflow = "NegFreeOverflow"
    """Negative free overflow"""
    ApplyFactorNo = "ApplyFactorNo"
    """Apply flow factor"""
    FactorValue = "FactorValue"
    """Flow factor [()]"""
    UpstreamSlope = "UpstreamSlope"
    """Upstream slope [()]"""
    DownstreamSlope = "DownstreamSlope"
    """Downstream slope [()]"""
    TopWidth = "TopWidth"
    """Top width [m]"""
    GrainDiameter = "GrainDiameter"
    """Grain diameter [m]"""
    SpecificGravity = "SpecificGravity"
    """Specific gravity [()]"""
    Porosity = "Porosity"
    """Porosity [()]"""
    CriticalStress = "CriticalStress"
    """Critical shear stress [N/m^2]"""
    SideErosionIndex = "SideErosionIndex"
    """Side erosion index [()]"""
    MinBottomLevel = "MinBottomLevel"
    """Minimum bottom level [m]"""
    MaxBottomWidth = "MaxBottomWidth"
    """Minimum bottom width [m]"""
    MaxBreachSlope = "MaxBreachSlope"
    """Maximum breach slope [()]"""
    InitialFailureTypeNo = "InitialFailureTypeNo"
    """Type of initial failure"""
    InitialLevel = "InitialLevel"
    """Initial level [m]"""
    InitialWidth = "InitialWidth"
    """Initial width [m]"""
    StartingLevel = "StartingLevel"
    """Starting level [m]"""
    InitialDiameter = "InitialDiameter"
    """Initial diameter [m]"""
    Roughness = "Roughness"
    """Roughness [m]"""
    CollapseRatio = "CollapseRatio"
    """Collapse ratio (D/y) [()]"""
    VolumeLossRatio = "VolumeLossRatio"
    """Volume loss ratio [()]"""
    CalibrationCoeff = "CalibrationCoeff"
    """Calibration coefficient [()]"""
    BreachLevelTypeNo = "BreachLevelTypeNo"
    """Breach level type"""
    BreachLevelConstant = "BreachLevelConstant"
    """Breach level constant [m]"""
    BreachLevelPath = "BreachLevelPath"
    """Breach level path"""
    BreachLevelItem = "BreachLevelItem"
    """Breach level item"""
    BreachWidthTypeNo = "BreachWidthTypeNo"
    """Breach width type"""
    BreachWidthConstant = "BreachWidthConstant"
    """Breach width constant [m]"""
    BreachWidthPath = "BreachWidthPath"
    """Breach width path"""
    BreachWidthItem = "BreachWidthItem"
    """Breach width item"""
    SlopeTypeNo = "SlopeTypeNo"
    """Slope type"""
    SlopeConstant = "SlopeConstant"
    """Slope constant [()]"""
    SlopePath = "SlopePath"
    """Slope path"""
    SlopeItem = "SlopeItem"
    """Slope item"""
    ApplyLimitingNo = "ApplyLimitingNo"
    """Apply limiting section"""
    ApplyRiverID = "ApplyRiverID"
    """River ID"""
    ApplyTopoID = "ApplyTopoID"
    """Topo ID"""
    ApplyChainage = "ApplyChainage"
    """Breach chainage"""
    ApplySCoordinate = "ApplySCoordinate"
    """S-coordinate of breach's center [m]"""
    PipeLevelTypeNo = "PipeLevelTypeNo"
    """Pipe level type"""
    PipeLevelConstant = "PipeLevelConstant"
    """Pipe level constant [m]"""
    PipeLevelPath = "PipeLevelPath"
    """Pipe level path"""
    PipeLevelItem = "PipeLevelItem"
    """Pipe level item"""
    DataSource = "DataSource"
    """Data source"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""

class mrm_DambreakTable(BaseGeometryTable):
    """Table for mrm_Dambreak (Dambreak)."""
    
    @property
    def columns(self) -> mrm_DambreakTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_DambreakTableColumns(self)
        return self._columns