from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mrm_BridgeOpeningTableColumns(BaseColumns):
    """Column names for mrm_BridgeOpening (mrm_BridgeOpening)."""
    MUID = "MUID"
    """ID"""
    RiverBridgeID = "RiverBridgeID"
    """River bridge ID"""
    Sqn = "Sqn"
    """Sqn"""
    Method = "Method"
    """Method"""
    AsymmetryChk = "AsymmetryChk"
    """Include asymmetric opening"""
    OpeningTypeNo = "OpeningTypeNo"
    """Opening type"""
    OpeningTypeRNo = "OpeningTypeRNo"
    """Opening type, right"""
    IncludePirNo = "IncludePirNo"
    """Include piers / piles"""
    PirWWBlock = "PirWWBlock"
    """Waterway blocked [()]"""
    PirUseCustomNo = "PirUseCustomNo"
    """Use custom table"""
    PirCustomTable = "PirCustomTable"
    """Custom table"""
    PileCustomTable1L = "PileCustomTable1L"
    """Custom table"""
    PileCustomTable2L = "PileCustomTable2L"
    """Custom table"""
    PirTypeNo = "PirTypeNo"
    """Type"""
    IncludeSknNo = "IncludeSknNo"
    """Include skewness"""
    SknAngle = "SknAngle"
    """Angle [deg]"""
    SknUseCustomNo = "SknUseCustomNo"
    """Use custom table"""
    SknCustomTable = "SknCustomTable"
    """Custom table"""
    IncludeEctrNo = "IncludeEctrNo"
    """Include eccentricity"""
    EctrUseCustomNo = "EctrUseCustomNo"
    """Use custom table"""
    EctrCustomTable = "EctrCustomTable"
    """Custom table"""
    IncludeSpdNo = "IncludeSpdNo"
    """Include spur dykes"""
    SpdLength = "SpdLength"
    """Length [m]"""
    SpdLengthR = "SpdLengthR"
    """Length [m]"""
    SpdTypeNo = "SpdTypeNo"
    """Type"""
    SpdTypeRNo = "SpdTypeRNo"
    """Type"""
    SpdAngle = "SpdAngle"
    """Angle [deg]"""
    SpdAngleR = "SpdAngleR"
    """Angle [deg]"""
    SpdOffset = "SpdOffset"
    """Offset [m]"""
    SpdOffsetR = "SpdOffsetR"
    """Offset [m]"""
    SpdUseCustom = "SpdUseCustom"
    """Use custom table"""
    SpdUseCustomR = "SpdUseCustomR"
    """Use custom tables, right"""
    SpdCustomTable1 = "SpdCustomTable1"
    """Table 1"""
    SpdCustomTableR1 = "SpdCustomTableR1"
    """Table 2"""
    SpdCustomTable2 = "SpdCustomTable2"
    """Table 1"""
    SpdCustomTableR2 = "SpdCustomTableR2"
    """Table 2"""
    RoughTypeNo = "RoughTypeNo"
    """Roughness type"""
    RoughValue = "RoughValue"
    """Roughness value"""
    RadioType = "RadioType"
    """Ratio"""
    WaterwayLength = "WaterwayLength"
    """Waterway length [m]"""
    WaterwayLengthR = "WaterwayLengthR"
    """Waterway length [m]"""
    LevelOfLength = "LevelOfLength"
    """Level of waterway length [m]"""
    LevelOfLengthR = "LevelOfLengthR"
    """Level of waterway length [m]"""
    ContractionLoss = "ContractionLoss"
    """Contraction loss coef. [()]"""
    ExpansionLoss = "ExpansionLoss"
    """Expansion loss coef. [()]"""
    OpeningWidth = "OpeningWidth"
    """Opening width [m]"""
    ArchesNum = "ArchesNum"
    """Number of arches"""
    LevelBottom = "LevelBottom"
    """Level of bottom of arch curvature [m]"""
    LevelTop = "LevelTop"
    """Level of top of arch curvature [m]"""
    Radius = "Radius"
    """Radius of arch curvature [m]"""
    UseCustomBaseNo = "UseCustomBaseNo"
    """Use custom table"""
    UseCustomBaseRNo = "UseCustomBaseRNo"
    """Use custom table"""
    CustomTableBase = "CustomTableBase"
    """Custom table"""
    CustomTableBaseR = "CustomTableBaseR"
    """Custom table"""
    UseCustomEntranNo = "UseCustomEntranNo"
    """Use custom table"""
    UseCustomEntranRNo = "UseCustomEntranRNo"
    """Use custom table"""
    CustomTableEntran = "CustomTableEntran"
    """Custom table"""
    CustomTableEntranR = "CustomTableEntranR"
    """Custom table"""
    EntranTypeNo = "EntranTypeNo"
    """Type"""
    EntranTypeRNo = "EntranTypeRNo"
    """Type"""
    EntranRadius = "EntranRadius"
    """Radius [m]"""
    EntranRadiusR = "EntranRadiusR"
    """Radius [m]"""
    EntranWidth = "EntranWidth"
    """Width [m]"""
    EntranWidthR = "EntranWidthR"
    """Width [m]"""
    EntranAngle = "EntranAngle"
    """Angle [deg]"""
    EntranAngleR = "EntranAngleR"
    """Angle [deg]"""
    EmbankSlope = "EmbankSlope"
    """Slope"""
    EmbankSlopeR = "EmbankSlopeR"
    """Slope"""
    UseCustromFroudeNo = "UseCustromFroudeNo"
    """Use custom table"""
    UseCustromFroudeRNo = "UseCustromFroudeRNo"
    """Use custom table"""
    CustromTableFroude = "CustromTableFroude"
    """Custom table"""
    CustromTableFroudeR = "CustromTableFroudeR"
    """Custom table"""
    UseCustromDepthNo = "UseCustromDepthNo"
    """Use custom table"""
    UseCustromDepthRNo = "UseCustromDepthRNo"
    """Use custom table"""
    CustromTableDepth = "CustromTableDepth"
    """Custom table"""
    CustromTableDepthR = "CustromTableDepthR"
    """Custom table"""
    UseCustromAbutNo = "UseCustromAbutNo"
    """Use custom table"""
    UseCustromAbutRNo = "UseCustromAbutRNo"
    """Use custom table"""
    CustromTableAbut = "CustromTableAbut"
    """Custom table"""
    CustromTableAbutR = "CustromTableAbutR"
    """Custom table"""
    UseCustromWWNo = "UseCustromWWNo"
    """Use custom table"""
    UseCustromWWRNo = "UseCustromWWRNo"
    """Use custom table"""
    CustromTableWW = "CustromTableWW"
    """Custom table"""
    CustromTableWWR = "CustromTableWWR"
    """Custom table"""
    WWAngle = "WWAngle"
    """Angle [deg]"""
    WWAngleR = "WWAngleR"
    """Angle [deg]"""
    TypeBaseNo = "TypeBaseNo"
    """Type"""
    UseCustromVelNo = "UseCustromVelNo"
    """Use custom table"""
    CustromTableVel = "CustromTableVel"
    """Custom table"""
    SubmergenceTypeNo = "SubmergenceTypeNo"
    """Include"""
    SubMgcMethodNo = "SubMgcMethodNo"
    """Method"""
    SubMgcDischargeCoef = "SubMgcDischargeCoef"
    """Discharge coef. [()]"""
    SubMgcUseCustomTableNo = "SubMgcUseCustomTableNo"
    """Use custom table"""
    SubMgcCustomTable = "SubMgcCustomTable"
    """Custom table"""
    SubMgcContraction = "SubMgcContraction"
    """Contraction loss [()]"""
    SubMgcExpansion = "SubMgcExpansion"
    """Expansion loss [()]"""
    SubMgcSoffitLevel = "SubMgcSoffitLevel"
    """Bridge soffit level [m]"""
    SubMgcCulvertID = "SubMgcCulvertID"
    """Culvert"""
    OflMethodNo = "OflMethodNo"
    """Method"""
    OflSurfaceNo = "OflSurfaceNo"
    """Surface"""
    OflUseCustomTableNo = "OflUseCustomTableNo"
    """Use custom table"""
    OflDischargeCoef1 = "OflDischargeCoef1"
    """Discharge coef #1"""
    OflDischargeCoef2 = "OflDischargeCoef2"
    """Discharge coef #2"""
    SubMgcFactor = "SubMgcFactor"
    """Submergence factor"""
    OflLength = "OflLength"
    """Length [m]"""
    OflDeckLevel = "OflDeckLevel"
    """Bridge deck level [m]"""
    OflWeirID = "OflWeirID"
    """Weir"""
    DatumUpCrs = "DatumUpCrs"
    """Datum [m]"""
    UseCustromCrsUpNo = "UseCustromCrsUpNo"
    """Use custom sub-cross section"""
    FromSUp = "FromSUp"
    """From S value [m]"""
    ToSUp = "ToSUp"
    """To S value [m]"""
    TableCrsUpID = "TableCrsUpID"
    """Custom table"""
    DownCrsTypeNo = "DownCrsTypeNo"
    """Cross section"""
    DownCrsSlope = "DownCrsSlope"
    """Slope [()]"""
    DatumDownCrs = "DatumDownCrs"
    """Datum [m]"""
    UseCustromCrsDownNo = "UseCustromCrsDownNo"
    """Use custom sub-cross section"""
    FromSDown = "FromSDown"
    """From S value [m]"""
    ToSDown = "ToSDown"
    """To S value [m]"""
    TableCrsDownID = "TableCrsDownID"
    """Custom table"""
    OffsetUSSection = "OffsetUSSection"
    """Horizontal offset for upstream bridge section [m]"""
    OffsetDSSection = "OffsetDSSection"
    """Horizontal offset for downstream bridge section [m]"""
    OffsetSub = "OffsetSub"
    """Horizontal offset for submergence level [m]"""
    OffsetOver = "OffsetOver"
    """Horizontal offset for overflow level [m]"""

class mrm_BridgeOpeningTable(BaseTable):
    """Table for mrm_BridgeOpening (mrm_BridgeOpening)."""
    
    @property
    def columns(self) -> mrm_BridgeOpeningTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_BridgeOpeningTableColumns(self)
        return self._columns