from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mrm_WeirTableColumns(BaseColumns):
    """Column names for mrm_Weir (Weirs)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    LinkID = "LinkID"
    """River ID"""
    Chainage = "Chainage"
    """Chainage [m]"""
    TypeNo = "TypeNo"
    """Weir type"""
    GeomType = "GeomType"
    """Geometry type"""
    Datum = "Datum"
    """Datum [m]"""
    GeomLinkID = "GeomLinkID"
    """Geometry link name"""
    GeomTopoID = "GeomTopoID"
    """Geometry topo ID"""
    GeomChainage = "GeomChainage"
    """Geometry chainage [m]"""
    GeomWidth = "GeomWidth"
    """Width [m]"""
    GeomHeight = "GeomHeight"
    """Height [m]"""
    InvertLevel = "InvertLevel"
    """Invert level [m]"""
    CrestLevel = "CrestLevel"
    """Crest level [m]"""
    Coeff = "Coeff"
    """Weir coefficient [()]"""
    ExpoCoeff = "ExpoCoeff"
    """Weir exponential coefficient [()]"""
    PO_i = "PO_i"
    """(hd/hu) i"""
    PO_a = "PO_a"
    """a"""
    PO_b = "PO_b"
    """b"""
    PO_p = "PO_p"
    """p"""
    IO_Alpha = "IO_Alpha"
    """Alpha"""
    IO_Beta = "IO_Beta"
    """Beta"""
    IO_q = "IO_q"
    """q"""
    SO_Gamma = "SO_Gamma"
    """Gamma"""
    SO_Delta = "SO_Delta"
    """Delta"""
    SO_s = "SO_s"
    """(hd/hu) s"""
    SO_r = "SO_r"
    """r"""
    HorizOffset = "HorizOffset"
    """Horizontal offset from marker 2 [m]"""
    NonReturnNo = "NonReturnNo"
    """Non return flap"""
    NonReturnTypeNo = "NonReturnTypeNo"
    """Non return flap type"""
    ApplyFactorNo = "ApplyFactorNo"
    """Apply flow factor"""
    FactorValue = "FactorValue"
    """Flow factor [()]"""
    PosInflow = "PosInflow"
    """Positive inflow"""
    PosOutflow = "PosOutflow"
    """Positive outflow"""
    PosFreeOverflow = "PosFreeOverflow"
    """Positive free overflow"""
    NegInflow = "NegInflow"
    """Negative inflow"""
    NegOutflow = "NegOutflow"
    """Negative outflow"""
    NegFreeOverflow = "NegFreeOverflow"
    """Negative free overflow"""
    HeadLossCmTypeNo = "HeadLossCmTypeNo"
    """Computational method"""
    AllowRecalculationNo = "AllowRecalculationNo"
    """Allow for recalculation"""
    NoQhRelations = "NoQhRelations"
    """No of Q/h relations"""
    DataSource = "DataSource"
    """Data source"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""

class mrm_WeirTable(BaseGeometryTable):
    """Table for mrm_Weir (Weirs)."""
    
    @property
    def columns(self) -> mrm_WeirTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mrm_WeirTableColumns(self)
        return self._columns