from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class ms_DPScheduleTableColumns(BaseColumns):
    """Column names for ms_DPSchedule (Profile calendars)."""
    MUID = "MUID"
    DaysNo = "DaysNo"
    WeekDay1 = "WeekDay1"
    WeekDay2 = "WeekDay2"
    WeekDay3 = "WeekDay3"
    WeekDay4 = "WeekDay4"
    WeekDay5 = "WeekDay5"
    WeekDay6 = "WeekDay6"
    WeekDay7 = "WeekDay7"
    DatesNo = "DatesNo"
    MonthDay1 = "MonthDay1"
    MonthDay2 = "MonthDay2"
    MonthDay3 = "MonthDay3"
    MonthDay4 = "MonthDay4"
    MonthDay5 = "MonthDay5"
    MonthDay6 = "MonthDay6"
    MonthDay7 = "MonthDay7"
    MonthDay8 = "MonthDay8"
    MonthDay9 = "MonthDay9"
    MonthDay10 = "MonthDay10"
    MonthDay11 = "MonthDay11"
    MonthDay12 = "MonthDay12"
    MonthDay13 = "MonthDay13"
    MonthDay14 = "MonthDay14"
    MonthDay15 = "MonthDay15"
    MonthDay16 = "MonthDay16"
    MonthDay17 = "MonthDay17"
    MonthDay18 = "MonthDay18"
    MonthDay19 = "MonthDay19"
    MonthDay20 = "MonthDay20"
    MonthDay21 = "MonthDay21"
    MonthDay22 = "MonthDay22"
    MonthDay23 = "MonthDay23"
    MonthDay24 = "MonthDay24"
    MonthDay25 = "MonthDay25"
    MonthDay26 = "MonthDay26"
    MonthDay27 = "MonthDay27"
    MonthDay28 = "MonthDay28"
    MonthDay29 = "MonthDay29"
    MonthDay30 = "MonthDay30"
    MonthDay31 = "MonthDay31"
    MonthsNo = "MonthsNo"
    Month1 = "Month1"
    Month2 = "Month2"
    Month3 = "Month3"
    Month4 = "Month4"
    Month5 = "Month5"
    Month6 = "Month6"
    Month7 = "Month7"
    Month8 = "Month8"
    Month9 = "Month9"
    Month10 = "Month10"
    Month11 = "Month11"
    Month12 = "Month12"

class ms_DPScheduleTable(BaseTable):
    """Table for ms_DPSchedule (Profile calendars)."""
    
    @property
    def columns(self) -> ms_DPScheduleTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = ms_DPScheduleTableColumns(self)
        return self._columns