from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class ms_DPScheduleTableColumns(BaseColumns):
    """Column names for ms_DPSchedule (Profile calendars)."""
    MUID = "MUID"
    """ID"""
    DaysNo = "DaysNo"
    """Week days"""
    WeekDay1 = "WeekDay1"
    """Monday"""
    WeekDay2 = "WeekDay2"
    """Tuesday"""
    WeekDay3 = "WeekDay3"
    """Wednesday"""
    WeekDay4 = "WeekDay4"
    """Thursday"""
    WeekDay5 = "WeekDay5"
    """Friday"""
    WeekDay6 = "WeekDay6"
    """Saturday"""
    WeekDay7 = "WeekDay7"
    """Sunday"""
    DatesNo = "DatesNo"
    """Dates"""
    MonthDay1 = "MonthDay1"
    """Day 1"""
    MonthDay2 = "MonthDay2"
    """Day 2"""
    MonthDay3 = "MonthDay3"
    """Day 3"""
    MonthDay4 = "MonthDay4"
    """Day 4"""
    MonthDay5 = "MonthDay5"
    """Day 5"""
    MonthDay6 = "MonthDay6"
    """Day 6"""
    MonthDay7 = "MonthDay7"
    """Day 7"""
    MonthDay8 = "MonthDay8"
    """Day 8"""
    MonthDay9 = "MonthDay9"
    """Day 9"""
    MonthDay10 = "MonthDay10"
    """Day 10"""
    MonthDay11 = "MonthDay11"
    """Day 11"""
    MonthDay12 = "MonthDay12"
    """Day 12"""
    MonthDay13 = "MonthDay13"
    """Day 13"""
    MonthDay14 = "MonthDay14"
    """Day 14"""
    MonthDay15 = "MonthDay15"
    """Day 15"""
    MonthDay16 = "MonthDay16"
    """Day 16"""
    MonthDay17 = "MonthDay17"
    """Day 17"""
    MonthDay18 = "MonthDay18"
    """Day 18"""
    MonthDay19 = "MonthDay19"
    """Day 19"""
    MonthDay20 = "MonthDay20"
    """Day 20"""
    MonthDay21 = "MonthDay21"
    """Day 21"""
    MonthDay22 = "MonthDay22"
    """Day 22"""
    MonthDay23 = "MonthDay23"
    """Day 23"""
    MonthDay24 = "MonthDay24"
    """Day 24"""
    MonthDay25 = "MonthDay25"
    """Day 25"""
    MonthDay26 = "MonthDay26"
    """Day 26"""
    MonthDay27 = "MonthDay27"
    """Day 27"""
    MonthDay28 = "MonthDay28"
    """Day 28"""
    MonthDay29 = "MonthDay29"
    """Day 29"""
    MonthDay30 = "MonthDay30"
    """Day 30"""
    MonthDay31 = "MonthDay31"
    """Day 31"""
    MonthsNo = "MonthsNo"
    """Months"""
    Month1 = "Month1"
    """January"""
    Month2 = "Month2"
    """February"""
    Month3 = "Month3"
    """March"""
    Month4 = "Month4"
    """April"""
    Month5 = "Month5"
    """May"""
    Month6 = "Month6"
    """June"""
    Month7 = "Month7"
    """July"""
    Month8 = "Month8"
    """August"""
    Month9 = "Month9"
    """September"""
    Month10 = "Month10"
    """October"""
    Month11 = "Month11"
    """November"""
    Month12 = "Month12"
    """December"""

class ms_DPScheduleTable(BaseTable):
    """Table for ms_DPSchedule (Profile calendars)."""
    
    @property
    def columns(self) -> ms_DPScheduleTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = ms_DPScheduleTableColumns(self)
        return self._columns