from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_RSSTableColumns(BaseColumns):
    """Column names for msm_RSS (Result selections)."""
    MUID = "MUID"
    """ID"""
    ResultSpecID = "ResultSpecID"
    """ResultSpecID"""
    SelectionNo = "SelectionNo"
    """Location type"""
    SubsetNo = "SubsetNo"
    """Subset type"""
    IndividualNo = "IndividualNo"
    """Individual type"""
    SelectionListID = "SelectionListID"
    """Selection ID"""
    ElementID = "ElementID"
    """Individual ID"""
    GridPointNo = "GridPointNo"
    """Save"""
    Chainage = "Chainage"
    """Location [m]"""
    InterpolationTypeNo = "InterpolationTypeNo"
    """Spatial interpolation type"""
    GridPointWettingNo = "GridPointWettingNo"
    """Save"""
    CellSize = "CellSize"
    """CellSize [m]"""
    Rotation = "Rotation"
    """Rotation [deg]"""
    ExtentDef = "ExtentDef"
    """ExtentDef"""
    LowerLeftX = "LowerLeftX"
    """LowerLeftX [m]"""
    LowerLeftY = "LowerLeftY"
    """LowerLeftY [m]"""
    LengthX = "LengthX"
    """LengthX [m]"""
    LengthY = "LengthY"
    """LengthY [m]"""
    NoCellsX = "NoCellsX"
    """NoCellsX"""
    NoCellsY = "NoCellsY"
    """NoCellsY"""
    WQComponentID = "WQComponentID"
    """WQ Component"""
    ItemNo = "ItemNo"
    """Item"""
    TypeNo = "TypeNo"
    """Type"""
    DrawOnMap = "DrawOnMap"
    """Draw on map"""
    FormatNo = "FormatNo"
    """Format"""
    FormatDelimiter = "FormatDelimiter"
    """Delimiter"""
    FormatColumnWidth = "FormatColumnWidth"
    """Column width"""
    FormatDecimalNum = "FormatDecimalNum"
    """Number of decimals"""
    FormatMaxNo = "FormatMaxNo"
    """Maximum"""
    FormatTimeMaxNo = "FormatTimeMaxNo"
    """Time of maximum"""
    FormatMinNo = "FormatMinNo"
    """Minimum"""
    FormatTimeMinNo = "FormatTimeMinNo"
    """Time of minimum"""

class msm_RSSTable(BaseTable):
    """Table for msm_RSS (Result selections)."""
    
    @property
    def columns(self) -> msm_RSSTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_RSSTableColumns(self)
        return self._columns