from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_ProjectTableColumns(BaseColumns):
    """Column names for msm_Project (Simulation setup)."""
    MUID = "MUID"
    """ID"""
    Sqn = "Sqn"
    """Sqn"""
    IncludeToBatchNo = "IncludeToBatchNo"
    """Include to batch"""
    ScenarioName = "ScenarioName"
    """Scenario"""
    ActiveProject = "ActiveProject"
    """Active simulation"""
    Enable_Catchment = "Enable_Catchment"
    """Catchments"""
    Enable_CS = "Enable_CS"
    """Collection system network"""
    Enable_River = "Enable_River"
    """River network"""
    Enable_2DOverland = "Enable_2DOverland"
    """2D Overland"""
    Enable_RR = "Enable_RR"
    """Rainfall-Runoff (RR)"""
    Enable_CD = "Enable_CD"
    """Catchment discharge (CD)"""
    Enable_HD = "Enable_HD"
    """Hydrodynamic (HD)"""
    Enable_LTS = "Enable_LTS"
    """Long term statistics (LTS)"""
    Enable_AD = "Enable_AD"
    """Transport (AD, SWQ)"""
    Enable_ECOLAB = "Enable_ECOLAB"
    """Water quality (MIKE ECO Lab)"""
    Enable_ST = "Enable_ST"
    """Sediment transport (ST)"""
    Enable_DA = "Enable_DA"
    """Data assimilation (DA)"""
    Enable_MHRiver_Coupling = "Enable_MHRiver_Coupling"
    """Coupling to MIKE HYDRO River"""
    Enable_M21FM_Coupling = "Enable_M21FM_Coupling"
    """Coupling to MIKE 21 or MIKE 3 FM"""
    ComputationBegin = "ComputationBegin"
    """Start"""
    ComputationEnd = "ComputationEnd"
    """End"""
    Description = "Description"
    """Description"""
    TADt = "TADt"
    """Time-Area [sec]"""
    KWDt = "KWDt"
    """Kin. wave [sec]"""
    UHMDt = "UHMDt"
    """UHM [sec]"""
    DtWetPeriod = "DtWetPeriod"
    """Wet weather [sec]"""
    DtDryPeriod = "DtDryPeriod"
    """Dry weather [sec]"""
    SRCDt = "SRCDt"
    """RDI [h]"""
    CDDt = "CDDt"
    """Catchment discharge [sec]"""
    DistribTypeNo = "DistribTypeNo"
    """Distribution type"""
    Power = "Power"
    """Power parameter"""
    SearchRadius = "SearchRadius"
    """Maximum search radius [km]"""
    RDIHotStartNo = "RDIHotStartNo"
    """Use RDII HotStart"""
    RDIHotStartFileName = "RDIHotStartFileName"
    """RDII HotStart filename"""
    RDIHotStartTimeUseNo = "RDIHotStartTimeUseNo"
    """Use simulation start time"""
    RDIHotStartTime = "RDIHotStartTime"
    """RDI hot start time"""
    ADPRunoffFileNo = "ADPRunoffFileNo"
    """Use ADP File"""
    ADPRunoffFileName = "ADPRunoffFileName"
    """ADP filename"""
    HDTimeStepType = "HDTimeStepType"
    """Time step"""
    HDDtFixed = "HDDtFixed"
    """Fixed [sec]"""
    HDDtMin = "HDDtMin"
    """Minimum [sec]"""
    HDDtMax = "HDDtMax"
    """Maximum [sec]"""
    HDDtIncreaseFactor = "HDDtIncreaseFactor"
    """Max. increase factor"""
    M2DHDMaxCFL = "M2DHDMaxCFL"
    """Max. CFL number [()]"""
    HDInitCondTypeNo = "HDInitCondTypeNo"
    """Type"""
    HDInitCondID = "HDInitCondID"
    """Initial conditions ID"""
    StateFilesFolder = "StateFilesFolder"
    """State files folder"""
    UseSimulationTypeNo = "UseSimulationTypeNo"
    """Select state file using simulation start time"""
    StateStartTime = "StateStartTime"
    """Date and time"""
    ADPNetworkFileNo = "ADPNetworkFileNo"
    """Apply Additional Parameters"""
    ADPNetworkFileName = "ADPNetworkFileName"
    """Additional parameters filename"""
    ADInitCondTypeNo = "ADInitCondTypeNo"
    """Type"""
    ADInitCondID = "ADInitCondID"
    """AD initial condition ID"""
    DecouplingADHDTypeNo = "DecouplingADHDTypeNo"
    """Decoupling of HD and AD simulations"""
    DecouplingPath = "DecouplingPath"
    """Decoupling file"""
    ELIntegrationNo = "ELIntegrationNo"
    """MIKE ECO Lab Integration"""
    ELUpdateFrequency = "ELUpdateFrequency"
    """MIKE ECO Lab update frequency"""
    M2DADDtMax = "M2DADDtMax"
    """Maximum [sec]"""
    M2DADDtMin = "M2DADDtMin"
    """Minimum [sec]"""
    M2DADMaxCFL = "M2DADMaxCFL"
    """Max. CFL number [()]"""
    MJLFileName = "MJLFileName"
    """LTS Job List"""
    HDOutputNo = "HDOutputNo"
    """Save results in default/this folder"""
    HDFolderPath = "HDFolderPath"
    """Result folder path"""
    SummaryID = "SummaryID"
    """Network summary"""

class msm_ProjectTable(BaseTable):
    """Table for msm_Project (Simulation setup)."""
    
    @property
    def columns(self) -> msm_ProjectTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_ProjectTableColumns(self)
        return self._columns