from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class msm_CulvertTableColumns(BaseColumns):
    """Column names for msm_Culvert (Culverts)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    LinkID = "LinkID"
    """River ID"""
    Chainage = "Chainage"
    """Chainage [m]"""
    GeomType = "GeomType"
    """Type"""
    IrregularTypeNo = "IrregularTypeNo"
    """Table type"""
    GeomWidth = "GeomWidth"
    """Width [m]"""
    GeomHeight = "GeomHeight"
    """Height [m]"""
    GeomDiameter = "GeomDiameter"
    """Diameter [m]"""
    GeomLinkID = "GeomLinkID"
    """Geometry link name"""
    GeomTopoID = "GeomTopoID"
    """Geometry topo ID"""
    GeomChainage = "GeomChainage"
    """Geometry chainage [m]"""
    UpstreamInvert = "UpstreamInvert"
    """Upstream invert [m]"""
    DownstreamInvert = "DownstreamInvert"
    """Downstream invert [m]"""
    Length = "Length"
    """Length [m]"""
    NumOfCulvert = "NumOfCulvert"
    """Number of culverts"""
    HorizOffset = "HorizOffset"
    """Horizontal offset from marker 2 [m]"""
    NonReturnNo = "NonReturnNo"
    """Non return flap"""
    NonReturnTypeNo = "NonReturnTypeNo"
    """Return flap type"""
    SectionTypeNo = "SectionTypeNo"
    """Section type"""
    ApplyFactorNo = "ApplyFactorNo"
    """Apply flow factor"""
    FactorValue = "FactorValue"
    """Flow factor [()]"""
    ManningN = "ManningN"
    """Manning's n [s/m^(1/3)]"""
    PosInflow = "PosInflow"
    """Positive inflow"""
    PosOutflow = "PosOutflow"
    """Positive outflow"""
    PosFreeOverflow = "PosFreeOverflow"
    """Positive free overflow"""
    PosBends = "PosBends"
    """Positive bends"""
    NegInflow = "NegInflow"
    """Negative inflow"""
    NegOutflow = "NegOutflow"
    """Negative outflow"""
    NegFreeOverflow = "NegFreeOverflow"
    """Negative free overflow"""
    NegBends = "NegBends"
    """Negative bends"""
    HeadLossCmTypeNo = "HeadLossCmTypeNo"
    """Computational method"""
    AllowRecalculationNo = "AllowRecalculationNo"
    """Allow for recalculation"""
    NoQhRelations = "NoQhRelations"
    """No. of Q/h relations"""
    DataSource = "DataSource"
    """Data source"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""

class msm_CulvertTable(BaseGeometryTable):
    """Table for msm_Culvert (Culverts)."""
    
    @property
    def columns(self) -> msm_CulvertTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_CulvertTableColumns(self)
        return self._columns