from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_HParBTableColumns(BaseColumns):
    """Column names for msm_HParB (Parameters kinematic wave)."""
    MUID = "MUID"
    """ID"""
    WetSteep = "WetSteep"
    """Wet Steep [mm]"""
    WetFlat = "WetFlat"
    """ Wet Flat [mm]"""
    WetSmall = "WetSmall"
    """Wet Small [mm]"""
    WetMedium = "WetMedium"
    """Wet Medium [mm]"""
    WetLarge = "WetLarge"
    """Wet Large [mm]"""
    StorageFlat = "StorageFlat"
    """Storage Flat [mm]"""
    StorageSmall = "StorageSmall"
    """Storage Small [mm]"""
    StorageMedium = "StorageMedium"
    """Storage Medium [mm]"""
    StorageLarge = "StorageLarge"
    """Storage Large [mm]"""
    InfMaxSmall = "InfMaxSmall"
    """InfMax Small [mm/h]"""
    InfMaxMedium = "InfMaxMedium"
    """InfMax Medium [mm/h]"""
    InfMaxLarge = "InfMaxLarge"
    """InfMax Large [mm/h]"""
    InfMinSmall = "InfMinSmall"
    """InfMin Small [mm/h]"""
    InfMinMedium = "InfMinMedium"
    """InfMin Medium [mm/h]"""
    InfMinLarge = "InfMinLarge"
    """InfMin Large [mm/h]"""
    InfExpWetSmall = "InfExpWetSmall"
    """InfExpWet Small [/s]"""
    InfExpWetMedium = "InfExpWetMedium"
    """InfExpWet Medium [/s]"""
    InfExpWetLarge = "InfExpWetLarge"
    """InfExpWet Large [/s]"""
    InfExpDrySmall = "InfExpDrySmall"
    """InfExpDry Small [/s]"""
    InfExpDryMedium = "InfExpDryMedium"
    """InfExpDry Medium [/s]"""
    InfExpDryLarge = "InfExpDryLarge"
    """InfExpDry Large [/s]"""
    FricTypeNo = "FricTypeNo"
    """Formulation"""
    ManningSteep = "ManningSteep"
    """Manning Steep"""
    ManningFlat = "ManningFlat"
    """Manning Flat"""
    ManningSmall = "ManningSmall"
    """Manning Small"""
    ManningMedium = "ManningMedium"
    """Manning Medium"""
    ManningLarge = "ManningLarge"
    """Manning Large"""

class msm_HParBTable(BaseTable):
    """Table for msm_HParB (Parameters kinematic wave)."""
    
    @property
    def columns(self) -> msm_HParBTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_HParBTableColumns(self)
        return self._columns