from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class msm_LinkTableColumns(BaseColumns):
    """Column names for msm_Link (Pipes and canals)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    TypeNo = "TypeNo"
    """Link type"""
    Height = "Height"
    """Height [m]"""
    Width = "Width"
    """Width [m]"""
    Diameter = "Diameter"
    """Diameter [m]"""
    Length = "Length"
    """Length [m]"""
    GeometricLength = "GeometricLength"
    """Geometric length [m]"""
    UpLevel = "UpLevel"
    """Upstream level [m]"""
    DwLevel = "DwLevel"
    """Downstream level [m]"""
    UpLevel_C = "UpLevel_C"
    """Upstream level (C) [m]"""
    DwLevel_C = "DwLevel_C"
    """Downstream level (C) [m]"""
    Slope = "Slope"
    """Slope [%]"""
    MaxDx = "MaxDx"
    """Max dx [m]"""
    CrsID = "CrsID"
    """Shape"""
    TopographyID = "TopographyID"
    """Topo ID"""
    FlowRegNo = "FlowRegNo"
    """Use flow regulation"""
    RegulationTypeNo = "RegulationTypeNo"
    """Regulation type"""
    FunctionID = "FunctionID"
    """Function ID"""
    ControlNodeAID = "ControlNodeAID"
    """Ctrl. node A"""
    ControlNodeBID = "ControlNodeBID"
    """Ctrl. node B"""
    NonReturnNo = "NonReturnNo"
    """Non return valve"""
    SpecLocalWaveNo = "SpecLocalWaveNo"
    """Use specified local wave approximation"""
    WaveApproximationTypeNo = "WaveApproximationTypeNo"
    """WaveApproximationTypeNo"""
    FricTypeNo = "FricTypeNo"
    """Resistance formulation"""
    FricNo = "FricNo"
    """Friction type"""
    MaterialID = "MaterialID"
    """Material ID"""
    Manning = "Manning"
    """Manning"""
    Rough = "Rough"
    """Roughness [m]"""
    HWCoef = "HWCoef"
    """H-W Coef."""
    ManTop = "ManTop"
    """Top"""
    ManBott = "ManBott"
    """Bottom"""
    ManExp = "ManExp"
    """Exponent"""
    PMApprNo = "PMApprNo"
    """Pressure main pipe"""
    SlotNo = "SlotNo"
    """Use specified Preissmann slot ratio"""
    Slot = "Slot"
    """Slot"""
    GridNo = "GridNo"
    """Use specified grid points number"""
    Grid = "Grid"
    """Grid [Integer]"""
    UseRoutingNo = "UseRoutingNo"
    """Used as Simple routing"""
    RoutingTypeNo = "RoutingTypeNo"
    """RoutingType"""
    RoutingDelay = "RoutingDelay"
    """RoutingDelay [min]"""
    RoutingShape = "RoutingShape"
    """RoutingShape [()]"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Element status"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""
    ChainageData = "ChainageData"
    """ChainageData"""

class msm_LinkTable(BaseGeometryTable):
    """Table for msm_Link (Pipes and canals)."""
    
    @property
    def columns(self) -> msm_LinkTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_LinkTableColumns(self)
        return self._columns