from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class msm_CatchmentTableColumns(BaseColumns):
    """Column names for msm_Catchment (Catchments)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    GeomCentroidX = "GeomCentroidX"
    """X coordinate [m]"""
    GeomCentroidY = "GeomCentroidY"
    """Y coordinate [m]"""
    Area = "Area"
    """Catchment area [ha]"""
    GeomArea = "GeomArea"
    """Geom area [ha]"""
    Persons = "Persons"
    """Person Equivalents [()]"""
    HydrologicalModelNo = "HydrologicalModelNo"
    """Hydrological model"""
    LossDefinition = "LossDefinition"
<<<<<<< HEAD
    """Use land use distribution"""
=======
    NewUKLandUseID = "NewUKLandUseID"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    ModelAImpArea = "ModelAImpArea"
    """ModelA impervious area [%]"""
    ModelALocalNo = "ModelALocalNo"
    """ModelA use local"""
    ModelAParAID = "ModelAParAID"
    """ModelA parameter ID"""
    ModelAConcTime = "ModelAConcTime"
    """ModelA concentration time [min]"""
    ModelARFactor = "ModelARFactor"
    """ModelA reduction factor [()]"""
    ModelAILoss = "ModelAILoss"
    """ModelA initial loss [mm]"""
    ModelACoeffNo = "ModelACoeffNo"
    """ModelA Coeff. No"""
    ModelATACurveID = "ModelATACurveID"
    """ModelA TA curve ID"""
    ModelATACoeff = "ModelATACoeff"
    """ModelA TA Coeff."""
    ModelBLength = "ModelBLength"
    """ModelB length [m]"""
    ModelBSlope = "ModelBSlope"
    """ModelB slope [o/oo]"""
    ModelBParBID = "ModelBParBID"
    """ModelB parameter ID"""
    ModelBAISteep = "ModelBAISteep"
    """ModelB AI steep [%]"""
    ModelBAIFlat = "ModelBAIFlat"
    """ModelB AI flat [%]"""
    ModelBAPSmall = "ModelBAPSmall"
    """ModelB AP Small [%]"""
    ModelBAPMedium = "ModelBAPMedium"
    """ModelB AP medium [%]"""
    ModelBAPLarge = "ModelBAPLarge"
    """ModelB AP large [%]"""
    ModelBLocalNo = "ModelBLocalNo"
    """ModelB use local"""
    FricTypeNo = "FricTypeNo"
    """Formulation"""
    ModelBMISteep = "ModelBMISteep"
    """ModelB MI steep"""
    ModelBMIFlat = "ModelBMIFlat"
    """ModelB MI flat"""
    ModelBMPSmall = "ModelBMPSmall"
    """ModelB MP Small"""
    ModelBMPMedium = "ModelBMPMedium"
    """ModelB MP medium"""
    ModelBMPLarge = "ModelBMPLarge"
    """ModelB MP large"""
    ModelC1EffectiveArea = "ModelC1EffectiveArea"
    """ModelC1 contributing area percentage [%]"""
    ModelC1LocalNo = "ModelC1LocalNo"
    """ModelC1 use local"""
    ModelC1ParCID = "ModelC1ParCID"
    """ModelC1 parameter ID"""
    ModelC1TimeConst = "ModelC1TimeConst"
    """ModelC1 time const [/h]"""
    ModelC1ILoss = "ModelC1ILoss"
    """ModelC1 inital loss [mm]"""
    ModelCLength = "ModelCLength"
    """ModelC length [m]"""
    ModelCSlope = "ModelCSlope"
    """ModelC slope [o/oo]"""
    ModelC2ImperviousArea = "ModelC2ImperviousArea"
    """ModelC2 impervious area [%]"""
    ModelC2LocalNo = "ModelC2LocalNo"
    """ModelC2 use local"""
    ModelC2ParCID = "ModelC2ParCID"
    """ModelC2 parameter ID"""
    ModelC2RedFactor = "ModelC2RedFactor"
    """ModelC2 reduction factor"""
    ModelC2ILoss = "ModelC2ILoss"
    """ModelC2 inital loss [mm]"""
    ModelC2LagTime = "ModelC2LagTime"
    """ModelC2 lag time [min]"""
    ModelC2TimeConst = "ModelC2TimeConst"
    """ModelC2 time const [/h]"""
    ModelUHMAreaFactor = "ModelUHMAreaFactor"
    """UHM Contributing area fraction"""
    ModelUHMMethodNo = "ModelUHMMethodNo"
    """UHM method"""
    ModelUHMHydrographTableID = "ModelUHMHydrographTableID"
    """Hydrograph table"""
    ModelUHMCp = "ModelUHMCp"
    """UHM Cp"""
    ModelUHMSuhSlope = "ModelUHMSuhSlope"
    """UHM Suh slope [%]"""
    ModelUHMLossModelNo = "ModelUHMLossModelNo"
    """ModelUHM loss model"""
    ModelUHMInitLoss = "ModelUHMInitLoss"
    """UHM inital loss [mm]"""
    ModelUHMConstLoss = "ModelUHMConstLoss"
    """UHM const loss [mm/h]"""
    ModelUHMRunoffCoeff = "ModelUHMRunoffCoeff"
    """UHM runoff Coeff."""
    ModelUHMCurveNum = "ModelUHMCurveNum"
    """UHM curve num"""
    ModelUHMAMC = "ModelUHMAMC"
    """UHM AMC"""
    ModelUHMInitAbstractDepth = "ModelUHMInitAbstractDepth"
    """UHM inital abstract depth [mm]"""
    ModelUHMLagTimeMethodNo = "ModelUHMLagTimeMethodNo"
    """UHM lag time method"""
    ModelUHMLagTime = "ModelUHMLagTime"
    """UHM lag time [h]"""
    ModelUHMHydraulicLength = "ModelUHMHydraulicLength"
    """UHM hydraulic length [m]"""
    ModelUHMLagCurveNum = "ModelUHMLagCurveNum"
    """UHM lag curve Num [Integer]"""
    ModelUHMSlope = "ModelUHMSlope"
    """UHM slope [%]"""
    ModelUHMSuhCt = "ModelUHMSuhCt"
    """UHM Suh Ct"""
    ModelUHMSuhL = "ModelUHMSuhL"
    """UHM Suh L [km]"""
    ModelUHMSuhLc = "ModelUHMSuhLc"
    """UHM Suh Lc [km]"""
    ModelUHMStreamSlope = "ModelUHMStreamSlope"
    """UHM stream slope [%]"""
    ModelUHMBasFactor = "ModelUHMBasFactor"
    """UHM basin factor"""
    AddFlowNo = "AddFlowNo"
    """Use additional flow"""
    AddFlow = "AddFlow"
    """Additional flow [m^3/s]"""
    RdiiArea = "RdiiArea"
    """RDI contributing area percentage [%]"""
    ParRdiiID = "ParRdiiID"
    """RDI parameter set"""
    IncludeAutoCalNo = "IncludeAutoCalNo"
<<<<<<< HEAD
    """Include autocalibration"""
=======
    NewUKInitAPI = "NewUKInitAPI"
    NewUKSoilDecayFactor = "NewUKSoilDecayFactor"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    SWMM_LoadToNo = "SWMM_LoadToNo"
    """Load to"""
    SWMM_OutletNodeID = "SWMM_OutletNodeID"
    """Load point ID"""
    SWMM_OutletCatchmentID = "SWMM_OutletCatchmentID"
    """Outlet catchment ID"""
    SWMM_RaingageID = "SWMM_RaingageID"
    """Rain gauge ID"""
    SWMM_Width = "SWMM_Width"
    """Width [m]"""
    SWMM_Slope = "SWMM_Slope"
    """Ground slope [o/oo]"""
    SWMM_Impervious = "SWMM_Impervious"
    """Imperviousness [()]"""
    SWMM_NImperv = "SWMM_NImperv"
    """Impervious manning [s/m^(1/3)]"""
    SWMM_NPerv = "SWMM_NPerv"
    """Pervious manning [s/m^(1/3)]"""
    SWMM_SnowPackID = "SWMM_SnowPackID"
    """Snowpack ID"""
    SWMM_NPervPatternID = "SWMM_NPervPatternID"
    """N-perv pattern"""
    SWMM_DstorePatternID = "SWMM_DstorePatternID"
    """Dstore pattern"""
    SWMM_DImperv = "SWMM_DImperv"
    """Imperv. d. storage [mm]"""
    SWMM_DPerv = "SWMM_DPerv"
    """Perv. d. storage [mm]"""
    SWMM_ImpervPctZero = "SWMM_ImpervPctZero"
    """% DCIA w/o d. storage [()]"""
    SWMM_RouteToNo = "SWMM_RouteToNo"
    """Subarea routing"""
    SWMM_PctRouted = "SWMM_PctRouted"
    """Percent routed [()]"""
    SWMM_CurbLength = "SWMM_CurbLength"
    """Curb length [m]"""
    SWMM_InfilPatternID = "SWMM_InfilPatternID"
<<<<<<< HEAD
    """Infil pattern"""
=======
    SWMM_InfilModelNo = "SWMM_InfilModelNo"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    SWMM_MaxRate = "SWMM_MaxRate"
    """Max infiltration rate [mm/h]"""
    SWMM_MinRate = "SWMM_MinRate"
    """Min infiltration rate [mm/h]"""
    SWMM_MaxInFil = "SWMM_MaxInFil"
    """Max infiltration vol. [mm]"""
    SWMM_DecayRate = "SWMM_DecayRate"
    """Decay rate [/s]"""
    SWMM_HRegen = "SWMM_HRegen"
    """DWF regeneration(Horton) [h]"""
    SWMM_Suction = "SWMM_Suction"
    """Soil capillary suction [m]"""
    SWMM_InitDef = "SWMM_InitDef"
    """Initial soil  moisture [()]"""
    SWMM_Conduct = "SWMM_Conduct"
    """Conductivity [m/s]"""
    SWMM_RunoffCN = "SWMM_RunoffCN"
    """Curve number [()]"""
    SWMM_CRegen = "SWMM_CRegen"
    """DWF regeneration(Curve No.) [h]"""
    SWMM_Tag = "SWMM_Tag"
    """Tag"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Element status"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""

class msm_CatchmentTable(BaseGeometryTable):
    """Table for msm_Catchment (Catchments)."""
    
    @property
    def columns(self) -> msm_CatchmentTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_CatchmentTableColumns(self)
        return self._columns