from mikeplus.tables.base_node_table import BaseNodeTable
from mikeplus.tables.base_node_table import BaseColumns

class msm_NodeTableColumns(BaseColumns):
    """Column names for msm_Node (Nodes)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    GeomX = "GeomX"
    """X [m]"""
    GeomY = "GeomY"
    """Y [m]"""
    TypeNo = "TypeNo"
    """Node type"""
    Diameter = "Diameter"
    """Diameter [m]"""
    GroundLevel = "GroundLevel"
    """Ground level [m]"""
    InvertLevel = "InvertLevel"
    """Bottom level [m]"""
    GeometryID = "GeometryID"
    """Basin geometry"""
    BranchID = "BranchID"
    """River ID"""
    BranchChainage = "BranchChainage"
    """Location [m]"""
    CoverTypeNo = "CoverTypeNo"
    """Cover type"""
    BufferPressure = "BufferPressure"
    """Buffer pressure [m]"""
    SpillCoef = "SpillCoef"
    """Spill coefficient"""
    ManholeCoverDisplacementID = "ManholeCoverDisplacementID"
    """Displacement table ID"""
    InletControlNo = "InletControlNo"
    """Use maximum inflow"""
    MaxInlet = "MaxInlet"
    """Max inlet [m^3/s]"""
    QHTypeNo = "QHTypeNo"
    """Use QH relation"""
    OutletQHID = "OutletQHID"
    """QH relation"""
    LossParID = "LossParID"
    """Head loss"""
    LossParNo = "LossParNo"
    """Use local parameters"""
    LossTypeNo = "LossTypeNo"
    """Loss type"""
    LossCoeffKm = "LossCoeffKm"
    """Loss coefficient Km"""
    LossCoeffContraction = "LossCoeffContraction"
    """Loss coefficient contraction"""
    LossCoeffTotal = "LossCoeffTotal"
    """Loss coefficient total"""
    EffAreaNo = "EffAreaNo"
    """Effect flow area"""
    PMTypeNo = "PMTypeNo"
    """Pressurized tail node"""
    PMLevel = "PMLevel"
    """Tail level [m]"""
    InfiltrationNo = "InfiltrationNo"
    """Infiltration method"""
    InitialWL = "InitialWL"
    """Initial water level [m]"""
    InfConstValue = "InfConstValue"
    """Infiltration rate [m/d]"""
    KfsSide = "KfsSide"
    """Kfs, side [m/d]"""
    PorosityFill = "PorosityFill"
    """Porosity of fill material"""
    KfsBottomNo = "KfsBottomNo"
    """Use kfs, bottom"""
    KfsBottom = "KfsBottom"
    """Kfs, bottom [m/d]"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    SubModelNo = "SubModelNo"
    """Model"""
    CriticalLevel = "CriticalLevel"
    """Critical level [m]"""
    Element_S = "Element_S"
    """Status"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""

class msm_NodeTable(BaseNodeTable):
    """Table for msm_Node (Nodes)."""
    
    @property
    def columns(self) -> msm_NodeTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_NodeTableColumns(self)
        return self._columns