from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_HParRDIITableColumns(BaseColumns):
    """Column names for msm_HParRDII (Parameters RDI)."""
    MUID = "MUID"
    """ID"""
    Umax = "Umax"
    """Max. content in surface storage (Umax) [mm]"""
    Lmax = "Lmax"
    """Max. content in root zone storage (Lmax) [mm]"""
    Cqof = "Cqof"
    """Overland runoff coefficient (CQOF) [()]"""
    GwCarea = "GwCarea"
    """Groundwater/catchment area ratio (Carea) [()]"""
    Ck = "Ck"
    """TC for routing overland flow (CK1,2)/(CK) [h]"""
    Ck2TypeNo = "Ck2TypeNo"
    """TC2 for routing overland flow (CK2)"""
    Ck2 = "Ck2"
    """TC2 overland flow value (CK2) [h]"""
    Ckif = "Ckif"
    """TC for interflow (CKIF) [h]"""
    Ckbf = "Ckbf"
    """TC for baseflow (CKBF) [h]"""
    Tof = "Tof"
    """Root zone fraction for overland flow (TOF) [()]"""
    Tif = "Tif"
    """Root zone fraction for interflow (TIF) [()]"""
    Tg = "Tg"
    """Root zone fraction for groundwater recharge (TG) [()]"""
    InitU = "InitU"
    """Surface storage (U) [mm]"""
    InitL = "InitL"
    """Root zone storage (L) [mm]"""
    InitGwl = "InitGwl"
    """Groundwater depth (GWL) [m]"""
    InitOf = "InitOf"
    """Overland flow (QOF) [mm/h]"""
    InitIf = "InitIf"
    """Interflow (QIF) [mm/h]"""
    InitBF = "InitBF"
    """Baseflow (BF) [m^3/s]"""
    InitBFLow = "InitBFLow"
    """Lower baseflow (BF-low) [m^3/s]"""
    SnowStorage = "SnowStorage"
    """Snow storage [mm]"""
    GwSy = "GwSy"
    """Specific yield of groundwater reservoir (Sy) [()]"""
    GwLmin = "GwLmin"
    """Min. groundwater depth below surface (GWLmin) [m]"""
    GWLbf0 = "GWLbf0"
    """Max. groundwater depth causing baseflow (GWLbf0) [m]"""
    GWLfl1 = "GWLfl1"
    """Groundwater depth for unit capillary flux (GWLfl1) [m]"""
    LowerBFTypeNo = "LowerBFTypeNo"
    """Use lower baseflow"""
    CQLow = "CQLow"
    """Recharge to groundwater (CQLow) [%]"""
    CKLow = "CKLow"
    """TC for routing lower baseflow (CKLow) [h]"""
    GWSeasonTypeNo = "GWSeasonTypeNo"
    """Seasonal variation of groundwater depth causing baseflow"""
    GWLBFMin = "GWLBFMin"
    """Min. GW depth for seasonal variation (GWLBF_min) [m]"""
    AbstractionTypeNo = "AbstractionTypeNo"
    """Use abstraction"""
    AbstractionSourceTypeNo = "AbstractionSourceTypeNo"
    """Pumped depth defined as"""
    SnowmeltNo = "SnowmeltNo"
    """Include snowmelt"""
    T0 = "T0"
    """Base temperature (T0) [deg C]"""
    SnowmeltC = "SnowmeltC"
    """Degree-day coefficient (Csnow) [mm/deg C/d]"""
    SnowmeltCTypeNo = "SnowmeltCTypeNo"
    """Degree-day coefficient type"""
    RadiationTypeNo = "RadiationTypeNo"
    """Use solar radiation"""
    RadiationCoef = "RadiationCoef"
    """Radiation coefficient [()]"""
    RainfallCoefTypeNo = "RainfallCoefTypeNo"
    """Use rainfall heat transfer"""
    RainfallCoef = "RainfallCoef"
    """Rainfall degree-day coefficient (Crain) [/deg C/d]"""
    ElevZonesNo = "ElevZonesNo"
    """Delineate catchment into elevation zones for snow modelling"""
    CorrectDryTempNo = "CorrectDryTempNo"
    """Correct temperature in dry condition"""
    CorrectDryTempCorrection = "CorrectDryTempCorrection"
    """Dry temperature correction [deg C/100m]"""
    CorrectWetTempNo = "CorrectWetTempNo"
    """Correct temperature in wet condition"""
    CorrectWetTempCorrection = "CorrectWetTempCorrection"
    """Wet temperature correction [deg C/100m]"""
    TempStationElev = "TempStationElev"
    """Reference elevation for temperature station [m]"""
    CorrectPrecNo = "CorrectPrecNo"
    """Correct precipitation rate"""
    CorrectPrecCorrection = "CorrectPrecCorrection"
    """Precipitation correction [%/100m]"""
    PrecStationElev = "PrecStationElev"
    """Reference elevation for precipitation station [m]"""
    IncludeIrrigationNo = "IncludeIrrigationNo"
    """Include Irrigation"""
    K0inf = "K0inf"
    """Infiltration rate at field capacity (K0inf) [mm/h]"""
    PClgw = "PClgw"
    """Local groundwater (PClgw) [%]"""
    PClr = "PClr"
    """Local river (PClr) [%]"""
    PCexr = "PCexr"
    """External river (PCexr) [%]"""
    RiverID = "RiverID"
    """River ID"""
    Chainage = "Chainage"
    """Chainage [m]"""
    IncludeSeasonalVarNo = "IncludeSeasonalVarNo"
    """Include seasonal variation of crop coefficients and operational losses"""
    ObjFuncWaterBalanceNo = "ObjFuncWaterBalanceNo"
    """Overall water balance"""
    ObjFuncRmsErrorNo = "ObjFuncRmsErrorNo"
    """Overall root mean square error"""
    ObjFuncPeakflowNo = "ObjFuncPeakflowNo"
    """Peak flow RMSE"""
    ObjFuncPeakflow = "ObjFuncPeakflow"
    """Peak flow [m^3/s]"""
    ObjFuncLowflowNo = "ObjFuncLowflowNo"
    """Low flow RMSE"""
    ObjFuncLowflow = "ObjFuncLowflow"
    """Low flow [m^3/s]"""
    ObjFuncMaxEvaluation = "ObjFuncMaxEvaluation"
    """Maximum number of evaluations"""
    ObjFuncInitDaysExcluded = "ObjFuncInitDaysExcluded"
    """Initial number of days excluded"""

class msm_HParRDIITable(BaseTable):
    """Table for msm_HParRDII (Parameters RDI)."""
    
    @property
    def columns(self) -> msm_HParRDIITableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_HParRDIITableColumns(self)
        return self._columns