from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_LIDcontrolTableColumns(BaseColumns):
    """Column names for msm_LIDcontrol (LID properties)."""
    MUID = "MUID"
    """ID"""
    LIDTypeNo = "LIDTypeNo"
    """Type"""
    StorHt = "StorHt"
    """Storage depth [mm]"""
    VegFrac = "VegFrac"
    """Vegetative cover"""
    FricTypeNo = "FricTypeNo"
    """Roughness formulation"""
    Rough = "Rough"
    """Surface roughness"""
    Slope = "Slope"
    """Surface slope [%]"""
    Xslope = "Xslope"
    """Swale side slope [%]"""
    SThick = "SThick"
    """Thickness [mm]"""
    Por = "Por"
    """Porosity"""
    FC = "FC"
    """Field capacity"""
    WP = "WP"
    """Wilting point"""
    SFlowCalculationNo = "SFlowCalculationNo"
    """Flow calculation"""
    LeakageCapacity = "LeakageCapacity"
    """Leak capacity [mm/h]"""
    InfiltrationCapacity = "InfiltrationCapacity"
    """Infiltration capacity [mm/h]"""
    Ksat = "Ksat"
    """Conductivity [mm/h]"""
    Kcoeff = "Kcoeff"
    """Conductivity slope"""
    Suct = "Suct"
    """Suction header [mm]"""
    PThick = "PThick"
    """Thickness [mm]"""
    PVPorosity = "PVPorosity"
    """Porosity"""
    FracImp = "FracImp"
    """Impervious surface"""
    Perm = "Perm"
    """Permeability [mm/h]"""
    PVclog = "PVclog"
    """Clogging factor"""
    Height = "Height"
    """Height [mm]"""
    SVPorosity = "SVPorosity"
    """Porosity"""
    Filt = "Filt"
    """Conductivity [mm/h]"""
    SVclog = "SVclog"
    """Clogging factor"""
    HOffset = "HOffset"
    """Offset height [mm]"""
    Delay = "Delay"
    """Delay [h]"""
    Expon = "Expon"
    """Exponent"""
    DrainCapacityTypeNo = "DrainCapacityTypeNo"
    """Drain capacity"""
    DrainCapacityArea = "DrainCapacityArea"
    """Capacity area [mm/h]"""
    DrainCapacityFlow = "DrainCapacityFlow"
    """Capacity flow [m^3/s]"""
    DMThick = "DMThick"
    """Thickness [mm]"""
    DMVPorosity = "DMVPorosity"
    """Porosity"""
    DMFricTypeNo = "DMFricTypeNo"
    """Roughness formulation"""
    DMRough = "DMRough"
    """Roughness"""

class msm_LIDcontrolTable(BaseTable):
    """Table for msm_LIDcontrol (LID properties)."""
    
    @property
    def columns(self) -> msm_LIDcontrolTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_LIDcontrolTableColumns(self)
        return self._columns