from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class msm_RTCSensorTableColumns(BaseColumns):
    """Column names for msm_RTCSensor (Sensors)."""
    MUID = "MUID"
    """ID"""
    Sqn = "Sqn"
    """Sqn"""
    TypeNo = "TypeNo"
    """Type"""
    ComponentID = "ComponentID"
    """WQ component"""
    LocationNo = "LocationNo"
    """Location type"""
    NodeLocationID = "NodeLocationID"
    """Node ID"""
    LinkLocationID = "LinkLocationID"
    """Link ID"""
    StorageLocationID = "StorageLocationID"
    """Storage ID"""
    WeirLocationID = "WeirLocationID"
    """Weir ID (CS)"""
    OrificeLocationID = "OrificeLocationID"
    """Orifice Gate ID"""
    ValveLocationID = "ValveLocationID"
    """Valve ID"""
    PumpLocationID = "PumpLocationID"
    """Pump ID (CS)"""
    ActionID = "ActionID"
    """Action ID"""
    RiverStructureTypeNo = "RiverStructureTypeNo"
    """Structure type"""
    RiverStructureID = "RiverStructureID"
    """Structure ID"""
    RiverLocationID = "RiverLocationID"
    """River ID"""
    UpStreamChainage = "UpStreamChainage"
    """Upstr. chainage [m]"""
    DownStreamChainage = "DownStreamChainage"
    """Downstr. chainage [m]"""
    GateLocationID = "GateLocationID"
    """Gate ID"""
    WeirRiverLocationID = "WeirRiverLocationID"
    """Weir ID (Rivers)"""
    CulvertRiverLocationID = "CulvertRiverLocationID"
    """Culvert ID"""
    DirectDischargeRiverLocationID = "DirectDischargeRiverLocationID"
    """Direct discharge ID"""
    PumpRiverLocationID = "PumpRiverLocationID"
    """Pump ID (Rivers)"""
    BridgeRiverLocationID = "BridgeRiverLocationID"
    """River bridge ID"""
    TabulatedRiverLocationID = "TabulatedRiverLocationID"
    """Tabulated ID"""
    DambreakRiverLocationID = "DambreakRiverLocationID"
    """Dambreak ID"""
    TSFileName = "TSFileName"
    """Time series file"""
    TSItemName = "TSItemName"
    """Time series item"""
    Chainage = "Chainage"
    """Chainage [m]"""
    Expression = "Expression"
    """Expression"""
    Description = "Description"
    """Description"""

class msm_RTCSensorTable(BaseTable):
    """Table for msm_RTCSensor (Sensors)."""
    
    @property
    def columns(self) -> msm_RTCSensorTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_RTCSensorTableColumns(self)
        return self._columns