from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class msm_PumpTableColumns(BaseColumns):
    """Column names for msm_Pump (Pumps)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    CapTypeNo = "CapTypeNo"
    """Pump type"""
    StartLevel = "StartLevel"
    """Start level [m]"""
    StopLevel = "StopLevel"
    """Stop level [m]"""
    AccTime = "AccTime"
    """Acc. time [sec]"""
    DecTime = "DecTime"
    """Dec. Time [sec]"""
    DutyPoint = "DutyPoint"
    """Constant flow [m^3/s]"""
    QMaxSetID = "QMaxSetID"
    """QMaxSet ID"""
    QMinSetID = "QMinSetID"
    """QMinSet ID"""
    OffSet1 = "OffSet1"
    """OffSet 1 [m]"""
    OffSet2 = "OffSet2"
    """OffSet 2 [m]"""
    RegNo = "RegNo"
    """Use Regulation"""
    ControlTypeNo = "ControlTypeNo"
    """Control type"""
    WetWellSetPoint = "WetWellSetPoint"
    """Wet Well setpoint [m]"""
    SpeedNo = "SpeedNo"
    """Speed"""
    MaxStartLevel = "MaxStartLevel"
    """Max. start level [m]"""
    MinStopLevel = "MinStopLevel"
    """Min. stop level [m]"""
    MinTimeOn = "MinTimeOn"
    """Min. time ON [min]"""
    MinTimeOff = "MinTimeOff"
    """Min. time OFF [min]"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""

class msm_PumpTable(BaseGeometryTable):
    """Table for msm_Pump (Pumps)."""
    
    @property
    def columns(self) -> msm_PumpTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = msm_PumpTableColumns(self)
        return self._columns