from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_AdjustmentTableColumns(BaseColumns):
    """Column names for mss_Adjustment (Climatology adjustments)."""
    MUID = "MUID"
    """ID"""
    Temp01 = "Temp01"
    """Temp in Jan [deg C]"""
    Temp02 = "Temp02"
    """Temp in Feb [deg C]"""
    Temp03 = "Temp03"
    """Temp in Mar [deg C]"""
    Temp04 = "Temp04"
    """Temp in Apr [deg C]"""
    Temp05 = "Temp05"
    """Temp in May [deg C]"""
    Temp06 = "Temp06"
    """Temp in June [deg C]"""
    Temp07 = "Temp07"
    """Temp in July [deg C]"""
    Temp08 = "Temp08"
    """Temp in Aug [deg C]"""
    Temp09 = "Temp09"
    """Temp in Sep [deg C]"""
    Temp10 = "Temp10"
    """Temp in Oct [deg C]"""
    Temp11 = "Temp11"
    """Temp in Nov [deg C]"""
    Temp12 = "Temp12"
    """Temp in Dec [deg C]"""
    Evap01 = "Evap01"
    """Evap in Jan [mm/d]"""
    Evap02 = "Evap02"
    """Evapin Feb [mm/d]"""
    Evap03 = "Evap03"
    """Evap in Mar [mm/d]"""
    Evap04 = "Evap04"
    """Value in Apr [mm/d]"""
    Evap05 = "Evap05"
    """Evap in May [mm/d]"""
    Evap06 = "Evap06"
    """Evap in June [mm/d]"""
    Evap07 = "Evap07"
    """Evap in July [mm/d]"""
    Evap08 = "Evap08"
    """Evap in Aug [mm/d]"""
    Evap09 = "Evap09"
    """Value in Sep [mm/d]"""
    Evap10 = "Evap10"
    """Evap in Oct [mm/d]"""
    Evap11 = "Evap11"
    """Evap in Nov [mm/d]"""
    Evap12 = "Evap12"
    """Evap in Dec [mm/d]"""
    Rain01 = "Rain01"
    """Rain in Jan"""
    Rain02 = "Rain02"
    """Rain in Feb"""
    Rain03 = "Rain03"
    """Rain in Mar"""
    Rain04 = "Rain04"
    """Rain in Apr"""
    Rain05 = "Rain05"
    """Rain in May"""
    Rain06 = "Rain06"
    """Rain in June"""
    Rain07 = "Rain07"
    """Rain in July"""
    Rain08 = "Rain08"
    """Rain in Aug"""
    Rain09 = "Rain09"
    """Rain in Sep"""
    Rain10 = "Rain10"
    """Rain in Oct"""
    Rain11 = "Rain11"
    """Rain in Nov"""
    Rain12 = "Rain12"
    """Rain in Dec"""
    Con01 = "Con01"
    """Cond in Jan"""
    Con02 = "Con02"
    """Cond in Feb"""
    Con03 = "Con03"
    """Cond in Mar"""
    Con04 = "Con04"
    """Cond in Apr"""
    Con05 = "Con05"
    """Cond in May"""
    Con06 = "Con06"
    """Cond in June"""
    Con07 = "Con07"
    """Cond in July"""
    Con08 = "Con08"
    """Cond in Aug"""
    Con09 = "Con09"
    """Cond in Sep"""
    Con10 = "Con10"
    """Cond in Oct"""
    Con11 = "Con11"
    """Cond in Nov"""
    Con12 = "Con12"
    """Cond in Dec"""

class mss_AdjustmentTable(BaseTable):
    """Table for mss_Adjustment (Climatology adjustments)."""
    
    @property
    def columns(self) -> mss_AdjustmentTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_AdjustmentTableColumns(self)
        return self._columns