from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_SnowPackTableColumns(BaseColumns):
    """Column names for mss_SnowPack (Snowpacks)."""
    MUID = "MUID"
    """ID"""
    Description = "Description"
    """Description"""
    Cmin1 = "Cmin1"
    """Cmin [mm/deg C/h]"""
    Cmax1 = "Cmax1"
    """Cmax [mm/deg C/h]"""
    Tbase1 = "Tbase1"
    """Tbase [deg C]"""
    Fwf1 = "Fwf1"
    """FWF"""
    Sd01 = "Sd01"
    """SD0 [mm]"""
    Fw01 = "Fw01"
    """FWF [mm]"""
    Snn0 = "Snn0"
    """SNN"""
    Cmin2 = "Cmin2"
    """Cmin [mm/deg C/h]"""
    Cmax2 = "Cmax2"
    """Cmax [mm/deg C/h]"""
    Tbase2 = "Tbase2"
    """Tbase [deg C]"""
    Fwf2 = "Fwf2"
    """FWF"""
    Sd02 = "Sd02"
    """SD0 [mm]"""
    Fw02 = "Fw02"
    """FW0 [mm]"""
    SD1002 = "SD1002"
    """SD100 [mm]"""
    Cmin3 = "Cmin3"
    """Cmin [mm/deg C/h]"""
    Cmax3 = "Cmax3"
    """Cmax [mm/deg C/h]"""
    Tbase3 = "Tbase3"
    """Tbase [deg C]"""
    Fwf3 = "Fwf3"
    """FWF"""
    Sd03 = "Sd03"
    """SD0 [mm]"""
    Fw03 = "Fw03"
    """FWF [mm]"""
    SD1003 = "SD1003"
    """SD100 [mm]"""
    Sdplow = "Sdplow"
    """SDplow [mm]"""
    Fout = "Fout"
    """Fout"""
    Fimperv = "Fimperv"
    """Fimperv"""
    Fperv = "Fperv"
    """Fperv"""
    Fimelt = "Fimelt"
    """Fimelt"""
    Fsubcatch = "Fsubcatch"
    """Fsubcatch"""
    SubCatchID = "SubCatchID"
    """SubcatchID"""

class mss_SnowPackTable(BaseTable):
    """Table for mss_SnowPack (Snowpacks)."""
    
    @property
    def columns(self) -> mss_SnowPackTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_SnowPackTableColumns(self)
        return self._columns