from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_ProjectTableColumns(BaseColumns):
    """Column names for mss_Project (Simulation setup)."""
    MUID = "MUID"
    """ID"""
    ScenarioName = "ScenarioName"
    """Scenario"""
    ActiveProject = "ActiveProject"
    """Active simulation"""
    UseRRNo = "UseRRNo"
    """Rainfall runoff"""
    UseRDNo = "UseRDNo"
    """Rainfall dependent I/I"""
    UseSMNo = "UseSMNo"
    """Snow melt"""
    UseGWNo = "UseGWNo"
    """Groundwater"""
    UseFRNo = "UseFRNo"
    """Flow routing (HD)"""
    Enable_2DOverland = "Enable_2DOverland"
    """2D Overland"""
    Enable_M21FM_Coupling = "Enable_M21FM_Coupling"
    """Coupling to MIKE 21 or MIKE 3 FM"""
    UseWQNo = "UseWQNo"
    """Water quality"""
    ComputationBegin = "ComputationBegin"
    """Start"""
    ComputationEnd = "ComputationEnd"
    """End"""
    Description = "Description"
    """Description"""
    RS_DryDay = "RS_DryDay"
    """Runoff step: Dry weather days"""
    RS_DryTime = "RS_DryTime"
    """Runoff step: Dry weather time"""
    RS_WetDay = "RS_WetDay"
    """Runoff step: Wet weather days"""
    RS_WetTime = "RS_WetTime"
    """Runoff step: Wet weather time"""
    InfiltrationModelNo = "InfiltrationModelNo"
    """Infiltration model"""
    RainfallFileNo = "RainfallFileNo"
    """Rainfall data"""
    RainfallFileUseSaveNo = "RainfallFileUseSaveNo"
    """Rainfall file user/save"""
    RainfallFileName = "RainfallFileName"
    """Rainfall file name"""
    RunoffFileSaveNo = "RunoffFileSaveNo"
    """Save runoff data"""
    RunoffFileSaveName = "RunoffFileSaveName"
    """Runoff data save file"""
    RDIIFileSaveNo = "RDIIFileSaveNo"
    """Save RDII data"""
    RDIIFileSaveName = "RDIIFileSaveName"
    """RDII data save file"""
    RoutingStep = "RoutingStep"
    """Routing step [sec]"""
    ControlRuleStep = "ControlRuleStep"
    """Control rule step"""
    RoutingModelNo = "RoutingModelNo"
    """Routing model"""
    AllowPondingNo = "AllowPondingNo"
    """Allow ponding"""
    MinConduitSlope = "MinConduitSlope"
    """Minimum conduit slope [%]"""
    SkipSteadyFlowPeriodNo = "SkipSteadyFlowPeriodNo"
    """Skip steady flow periods"""
    SysFlowTolerance = "SysFlowTolerance"
    """System flow tolerance [%]"""
    LatFlowTolerance = "LatFlowTolerance"
    """Lateral flow tolerance [%]"""
    HotstartFileSaveNo = "HotstartFileSaveNo"
    """Save hotstart data"""
    HotstartFileSaveName = "HotstartFileSaveName"
    """Hotstart save file name"""
    HotstartFileUseNo = "HotstartFileUseNo"
    """Use hotstart data"""
    HotstartFileUseName = "HotstartFileUseName"
    """Hotstart use file name"""
    InflowFileUseNo = "InflowFileUseNo"
    """Use inflow data"""
    InflowFileUseName = "InflowFileUseName"
    """Inflow file name"""
    OutflowFileSaveNo = "OutflowFileSaveNo"
    """Save outflow data"""
    OutflowFileSaveName = "OutflowFileSaveName"
    """Outflow file name"""
    RDIIFileUseNo = "RDIIFileUseNo"
    """Use RDII data"""
    RDIIFileUseName = "RDIIFileUseName"
    """RDII file name"""
    RunoffFileUseNo = "RunoffFileUseNo"
    """Use runoff data"""
    RunoffFileUseName = "RunoffFileUseName"
    """Runoff file name"""
    InertialTermNo = "InertialTermNo"
    """Inertial terms"""
    NormalFlowCritNo = "NormalFlowCritNo"
    """Normal flow criterion"""
    ForceMainEqNo = "ForceMainEqNo"
    """Force main equation"""
    SurchargeMethodNo = "SurchargeMethodNo"
    """Surcharge method"""
    UseVarTSNo = "UseVarTSNo"
    """Use variable time steps adjusted by"""
    VarTSAdjustBy = "VarTSAdjustBy"
    """Use variable time steps adjusted by [%]"""
    MinVarTS = "MinVarTS"
    """Minimum variable time step [sec]"""
    ConduitLenTS = "ConduitLenTS"
    """Time step for conduit lengthening [sec]"""
    MinNodalSurfaceArea = "MinNodalSurfaceArea"
    """Minimum nodal surface area [m^2]"""
    MaxTrialPerTS = "MaxTrialPerTS"
    """Maximum trials per time step"""
    HeadConvergenceTolerance = "HeadConvergenceTolerance"
    """Head convergence tolerance [m]"""
    StartSweep = "StartSweep"
    """Start sweeping on"""
    EndSweep = "EndSweep"
    """End sweeping on"""
    AntecedentDryDay = "AntecedentDryDay"
    """Antecedent dry days"""
    HDOutputNo = "HDOutputNo"
    """Save results in default/this folder"""
    HDFolderPath = "HDFolderPath"
    """Result folder path"""
    HDFileName = "HDFileName"
    """HD file name"""
    Report_Timestep = "Report_Timestep"
    """Report time step [sec]"""
    Report_StartTime = "Report_StartTime"
    """Report start time"""
    SubCatchmentsNo = "SubCatchmentsNo"
    """Subcatchments summary"""
    SubCatchmentFileName = "SubCatchmentFileName"
    """Subcatchment list"""
    NodesNo = "NodesNo"
    """Nodes summary"""
    NodesFileName = "NodesFileName"
    """Nodes list"""
    LinksNo = "LinksNo"
    """Links summary"""
    LinksFileName = "LinksFileName"
    """Links list"""
    ReportInputNo = "ReportInputNo"
    """Input summary"""
    ReportControlNo = "ReportControlNo"
    """Control summary"""
    ReportAverageNo = "ReportAverageNo"
    """Average summary"""
    FlowStatsNo = "FlowStatsNo"
    """Flow statistics"""
    ControlsNo = "ControlsNo"
    """Control actions"""
    ContinuityNo = "ContinuityNo"
    """Continuity check"""
    M2DHDDtMax = "M2DHDDtMax"
    """Maximum [sec]"""
    M2DHDDtMin = "M2DHDDtMin"
    """Minimum [sec]"""
    M2DHDMaxCFL = "M2DHDMaxCFL"
    """Max. CFL factor [()]"""
    M2DADDtMax = "M2DADDtMax"
    """Maximum [sec]"""
    M2DADDtMin = "M2DADDtMin"
    """Minimum [sec]"""
    M2DADMaxCFL = "M2DADMaxCFL"
    """Max. CFL factor [()]"""
    M2DHDOutputNo = "M2DHDOutputNo"
    """Save results in default/this folder"""
    M2DHDFolderPath = "M2DHDFolderPath"
    """Result folder path"""

class mss_ProjectTable(BaseTable):
    """Table for mss_Project (Simulation setup)."""
    
    @property
    def columns(self) -> mss_ProjectTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_ProjectTableColumns(self)
        return self._columns