from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mss_LinkTableColumns(BaseColumns):
    """Column names for mss_Link (Conduits)."""
    MUID = "MUID"
    """ID"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    ShapeTypeNo = "ShapeTypeNo"
    """Conduit shape"""
    Length = "Length"
    """Length [m]"""
    GeometricLength = "GeometricLength"
    """Geometric length [m]"""
    InletInvert = "InletInvert"
    """Inlet invert elevation [m]"""
    OutletInvert = "OutletInvert"
    """Outlet invert elevation [m]"""
    InletInvert_C = "InletInvert_C"
    """Inlet invert elevation (C) [m]"""
    OutletInvert_C = "OutletInvert_C"
    """Outlet invert elevation (C) [m]"""
    InletInvert_Offset = "InletInvert_Offset"
    """Inlet invert offset [m]"""
    OutletInvert_Offset = "OutletInvert_Offset"
    """Outlet invert offset [m]"""
    Depth = "Depth"
    """Max. height [m]"""
    SedimentDepth = "SedimentDepth"
    """Sediment depth [m]"""
    BottomWidth = "BottomWidth"
    """Bottom / Max width [m]"""
    TopWidth = "TopWidth"
    """Top / Max Width [m]"""
    LeftSideSlope = "LeftSideSlope"
    """Left side slope [%]"""
    TriangleHeight = "TriangleHeight"
    """Triangle height"""
    BottomRadius = "BottomRadius"
    """Bottom radius [m]"""
    Barrels = "Barrels"
    """Number of barrels"""
    RightSideSlope = "RightSideSlope"
    """Right side slope [%]"""
    Slope = "Slope"
    """Slope [%]"""
    Exponent = "Exponent"
    """Exponent"""
    SidewallsNo = "SidewallsNo"
    """Removed sidewalls"""
    TransectID = "TransectID"
    """Transect ID"""
    ShapeID = "ShapeID"
    """Shape ID"""
    FricNo = "FricNo"
    """Friction type"""
    MaterialID = "MaterialID"
    """Material ID"""
    Roughness = "Roughness"
    """Manning roughness [s/m^(1/3)]"""
    AvgLossCoeff = "AvgLossCoeff"
    """Average losscoeff"""
    ForceMainRoughnessHW = "ForceMainRoughnessHW"
    """H-W roughness"""
    ForceMainRoughnessDW = "ForceMainRoughnessDW"
    """D-W roughness [mm]"""
    EntryLossCoeff = "EntryLossCoeff"
    """Entry loss coeff"""
    ExitLossCoeff = "ExitLossCoeff"
    """Exit loss coeff"""
    FlapGateNo = "FlapGateNo"
    """Flap gate"""
    InitialFlow = "InitialFlow"
    """Initial flow [m^3/s]"""
    MaxFlow = "MaxFlow"
    """Max flow [m^3/s]"""
    CulvertCode = "CulvertCode"
    """Culvert code"""
    SeepageRate = "SeepageRate"
    """Seepage rate [mm/h]"""
    AssetName = "AssetName"
    """Asset ID"""
    DataSource = "DataSource"
    """Data source"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""
    Tag = "Tag"
    """Tag"""
    Enabled = "Enabled"
    """Is active"""
    Element_S = "Element_S"
    """Element_S"""

class mss_LinkTable(BaseGeometryTable):
    """Table for mss_Link (Conduits)."""
    
    @property
    def columns(self) -> mss_LinkTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_LinkTableColumns(self)
        return self._columns