from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mss_WeirTableColumns(BaseColumns):
    """Column names for mss_Weir (Weirs)."""
    MUID = "MUID"
    """ID"""
    Enabled = "Enabled"
    """Apply"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    TypeNo = "TypeNo"
    """Type"""
    InvertLevel = "InvertLevel"
    """Coefficient"""
    Height = "Height"
    """Opening [m]"""
    Length = "Length"
    """Length [m]"""
    SideSlope = "SideSlope"
    """Side slope"""
    CrestHeight = "CrestHeight"
    """Crest elevation"""
    DischargeCoeff = "DischargeCoeff"
    """Discharge coeff"""
    DischargeCoeff_RoadWay = "DischargeCoeff_RoadWay"
    """Discharge coeff(roadway)"""
    DischargeCoeff_SideFlow = "DischargeCoeff_SideFlow"
    """Discharge coeff(sideflow)"""
    DischargeCoeff_V = "DischargeCoeff_V"
    """Discharge coeff(V-Notch)"""
    FlapGateNo = "FlapGateNo"
    """Flap gate"""
    CanSurchargeNo = "CanSurchargeNo"
    """Can surcharge"""
    NoEndContractions = "NoEndContractions"
    """No. end contractions"""
    CoeffCurveID = "CoeffCurveID"
    """Coefficient curve"""
    Cd2 = "Cd2"
    """End coeff [m^3/s]"""
    RoadWidth = "RoadWidth"
    """Road width [m]"""
    RoadSurf = "RoadSurf"
    """Road surface"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    NetTypeNo = "NetTypeNo"
    """Network type"""
    Description = "Description"
    """Description"""
    Tag = "Tag"
    """Tag"""

class mss_WeirTable(BaseGeometryTable):
    """Table for mss_Weir (Weirs)."""
    
    @property
    def columns(self) -> mss_WeirTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_WeirTableColumns(self)
        return self._columns