from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_PatternTableColumns(BaseColumns):
    """Column names for mss_Pattern (Time patterns)."""
    MUID = "MUID"
    """ID"""
    TypeNo = "TypeNo"
    """Type"""
    Description = "Description"
    """Description"""
    Mdr1 = "Mdr1"
    """January"""
    Mdr2 = "Mdr2"
    """February"""
    Mdr3 = "Mdr3"
    """March"""
    Mdr4 = "Mdr4"
    """April"""
    Mdr5 = "Mdr5"
    """May"""
    Mdr6 = "Mdr6"
    """June"""
    Mdr7 = "Mdr7"
    """July"""
    Mdr8 = "Mdr8"
    """August"""
    Mdr9 = "Mdr9"
    """September"""
    Mdr10 = "Mdr10"
    """October"""
    Mdr11 = "Mdr11"
    """November"""
    Mdr12 = "Mdr12"
    """December"""
    Day1 = "Day1"
    """Monday"""
    Day2 = "Day2"
    """Tuesday"""
    Day3 = "Day3"
    """Wednesday"""
    Day4 = "Day4"
    """Thursday"""
    Day5 = "Day5"
    """Friday"""
    Day6 = "Day6"
    """Saturday"""
    Day7 = "Day7"
    """Sunday"""
    AM12 = "AM12"
    """Week AM 12"""
    AM1 = "AM1"
    """Week AM 01"""
    AM2 = "AM2"
    """Week AM 02"""
    AM3 = "AM3"
    """Week AM 03"""
    AM4 = "AM4"
    """Week AM 04"""
    AM5 = "AM5"
    """Week AM 05"""
    AM6 = "AM6"
    """Week AM 06"""
    AM7 = "AM7"
    """Week AM 07"""
    AM8 = "AM8"
    """Week AM 08"""
    AM9 = "AM9"
    """Week AM 09"""
    AM10 = "AM10"
    """Week AM 10"""
    AM11 = "AM11"
    """Week AM 11"""
    PM12 = "PM12"
    """Week PM 12"""
    PM1 = "PM1"
    """Week PM 01"""
    PM2 = "PM2"
    """Week PM 02"""
    PM3 = "PM3"
    """Week PM 03"""
    PM4 = "PM4"
    """Week PM 04"""
    PM5 = "PM5"
    """Week PM 05"""
    PM6 = "PM6"
    """Week PM 06"""
    PM7 = "PM7"
    """Week PM 07"""
    PM8 = "PM8"
    """Week PM 08"""
    PM9 = "PM9"
    """Week PM 09"""
    PM10 = "PM10"
    """Week PM 10"""
    PM11 = "PM11"
    """Week PM 11"""
    AMW12 = "AMW12"
    """Weekend AM 12"""
    AMW1 = "AMW1"
    """Weekend AM 01"""
    AMW2 = "AMW2"
    """Weekend AM 02"""
    AMW3 = "AMW3"
    """Weekend AM 03"""
    AMW4 = "AMW4"
    """Weekend AM 04"""
    AMW5 = "AMW5"
    """Weekend AM 05"""
    AMW6 = "AMW6"
    """Weekend AM 06"""
    AMW7 = "AMW7"
    """Weekend AM 07"""
    AMW8 = "AMW8"
    """Weekend AM 08"""
    AMW9 = "AMW9"
    """Weekend AM 09"""
    AMW10 = "AMW10"
    """Weekend AM 10"""
    AMW11 = "AMW11"
    """Weekend AM 11"""
    PMW12 = "PMW12"
    """Weekend PM 12"""
    PMW1 = "PMW1"
    """Weekend PM 01"""
    PMW2 = "PMW2"
    """Weekend PM 02"""
    PMW3 = "PMW3"
    """Weekend PM 03"""
    PMW4 = "PMW4"
    """Weekend PM 04"""
    PMW5 = "PMW5"
    """Weekend PM 05"""
    PMW6 = "PMW6"
    """Weekend PM 06"""
    PMW7 = "PMW7"
    """Weekend PM 07"""
    PMW8 = "PMW8"
    """Weekend PM 08"""
    PMW9 = "PMW9"
    """Weekend PM 09"""
    PMW10 = "PMW10"
    """Weekend PM 10"""
    PMW11 = "PMW11"
    """Weekend PM 11"""

class mss_PatternTable(BaseTable):
    """Table for mss_Pattern (Time patterns)."""
    
    @property
    def columns(self) -> mss_PatternTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_PatternTableColumns(self)
        return self._columns