from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_TemperatureTableColumns(BaseColumns):
    """Column names for mss_Temperature (Climatology)."""
    MUID = "MUID"
    """ID"""
    TypeNo = "TypeNo"
    """Type"""
    TimeSeriesID = "TimeSeriesID"
    """Time series ID"""
    FileName = "FileName"
    """Climatological file (NCDC)"""
    StartNo = "StartNo"
    """Start reading file at"""
    StartDate = "StartDate"
    """Start reading file at"""
    WindSpeedTypeNo = "WindSpeedTypeNo"
    """Wind speed type"""
    Value1 = "Value1"
    """Speed in Jan [km/h]"""
    Value2 = "Value2"
    """Speed in Feb [km/h]"""
    Value3 = "Value3"
    """Speed in Mar [km/h]"""
    Value4 = "Value4"
    """Speed in Apr [km/h]"""
    Value5 = "Value5"
    """Speed in May [km/h]"""
    Value6 = "Value6"
    """Speed in June [km/h]"""
    Value7 = "Value7"
    """Speed in July [km/h]"""
    Value8 = "Value8"
    """Speed in Aug [km/h]"""
    Value9 = "Value9"
    """Speed in Sep [km/h]"""
    Value10 = "Value10"
    """Speed in Oct [km/h]"""
    Value11 = "Value11"
    """Speed in Nov [km/h]"""
    Value12 = "Value12"
    """Speed in Dec [km/h]"""
    SnowTemp = "SnowTemp"
    """Dividing temperature between snow and rain [deg C]"""
    Atiwt = "Atiwt"
    """ATI weight"""
    Rnm = "Rnm"
    """Negative melt ratio"""
    Elev = "Elev"
    """Elevation above MSL [m]"""
    Lat = "Lat"
    """Latitude [degN50]"""
    Dtlong = "Dtlong"
    """Longitude correction [min]"""
    ADCNo = "ADCNo"
    """ADC type"""
    AdcPerv0 = "AdcPerv0"
    """AdcPerv0"""
    AdcPerv1 = "AdcPerv1"
    """AdcPerv1"""
    AdcPerv2 = "AdcPerv2"
    """AdcPerv2"""
    AdcPerv3 = "AdcPerv3"
    """AdcPerv3"""
    AdcPerv4 = "AdcPerv4"
    """AdcPerv4"""
    AdcPerv5 = "AdcPerv5"
    """AdcPerv5"""
    AdcPerv6 = "AdcPerv6"
    """AdcPerv6"""
    AdcPerv7 = "AdcPerv7"
    """AdcPerv7"""
    AdcPerv8 = "AdcPerv8"
    """AdcPerv8"""
    AdcPerv9 = "AdcPerv9"
    """AdcPerv9"""
    AdcImPerv0 = "AdcImPerv0"
    """AdcImPerv0"""
    AdcImPerv1 = "AdcImPerv1"
    """AdcImPerv1"""
    AdcImPerv2 = "AdcImPerv2"
    """AdcImPerv2"""
    AdcImPerv3 = "AdcImPerv3"
    """AdcImPerv3"""
    AdcImPerv4 = "AdcImPerv4"
    """AdcImPerv4"""
    AdcImPerv5 = "AdcImPerv5"
    """AdcImPerv5"""
    AdcImPerv6 = "AdcImPerv6"
    """AdcImPerv6"""
    AdcImPerv7 = "AdcImPerv7"
    """AdcImPerv7"""
    AdcImPerv8 = "AdcImPerv8"
    """AdcImPerv8"""
    AdcImPerv9 = "AdcImPerv9"
    """AdcImPerv9"""

class mss_TemperatureTable(BaseTable):
    """Table for mss_Temperature (Climatology)."""
    
    @property
    def columns(self) -> mss_TemperatureTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_TemperatureTableColumns(self)
        return self._columns