from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mss_PatternTableColumns(BaseColumns):
    """Column names for mss_Pattern (Time patterns)."""
    MUID = "MUID"
    TypeNo = "TypeNo"
    Description = "Description"
    Mdr1 = "Mdr1"
    Mdr2 = "Mdr2"
    Mdr3 = "Mdr3"
    Mdr4 = "Mdr4"
    Mdr5 = "Mdr5"
    Mdr6 = "Mdr6"
    Mdr7 = "Mdr7"
    Mdr8 = "Mdr8"
    Mdr9 = "Mdr9"
    Mdr10 = "Mdr10"
    Mdr11 = "Mdr11"
    Mdr12 = "Mdr12"
    Day1 = "Day1"
    Day2 = "Day2"
    Day3 = "Day3"
    Day4 = "Day4"
    Day5 = "Day5"
    Day6 = "Day6"
    Day7 = "Day7"
    AM12 = "AM12"
    AM1 = "AM1"
    AM2 = "AM2"
    AM3 = "AM3"
    AM4 = "AM4"
    AM5 = "AM5"
    AM6 = "AM6"
    AM7 = "AM7"
    AM8 = "AM8"
    AM9 = "AM9"
    AM10 = "AM10"
    AM11 = "AM11"
    PM12 = "PM12"
    PM1 = "PM1"
    PM2 = "PM2"
    PM3 = "PM3"
    PM4 = "PM4"
    PM5 = "PM5"
    PM6 = "PM6"
    PM7 = "PM7"
    PM8 = "PM8"
    PM9 = "PM9"
    PM10 = "PM10"
    PM11 = "PM11"
    AMW12 = "AMW12"
    AMW1 = "AMW1"
    AMW2 = "AMW2"
    AMW3 = "AMW3"
    AMW4 = "AMW4"
    AMW5 = "AMW5"
    AMW6 = "AMW6"
    AMW7 = "AMW7"
    AMW8 = "AMW8"
    AMW9 = "AMW9"
    AMW10 = "AMW10"
    AMW11 = "AMW11"
    PMW12 = "PMW12"
    PMW1 = "PMW1"
    PMW2 = "PMW2"
    PMW3 = "PMW3"
    PMW4 = "PMW4"
    PMW5 = "PMW5"
    PMW6 = "PMW6"
    PMW7 = "PMW7"
    PMW8 = "PMW8"
    PMW9 = "PMW9"
    PMW10 = "PMW10"
    PMW11 = "PMW11"

class mss_PatternTable(BaseTable):
    """Table for mss_Pattern (Time patterns)."""
    
    @property
    def columns(self) -> mss_PatternTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mss_PatternTableColumns(self)
        return self._columns