from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mw_FlushingTableColumns(BaseColumns):
    """Column names for mw_Flushing (Flushing analysis)."""
    MUID = "MUID"
    """ID"""
    TypeNo = "TypeNo"
    """Type"""
    Sqn = "Sqn"
    """Sqn"""
    OutputPath = "OutputPath"
    """Output path"""
    PipeList = "PipeList"
    """Pipe list"""
    TargetTypeNo = "TargetTypeNo"
    """Target type no"""
    TargetVelocity = "TargetVelocity"
    """Target velocity [m/s]"""
    TargetShearStr = "TargetShearStr"
    """Target shear stress [N/m^2]"""
    MinResidualPre = "MinResidualPre"
    """Minimum residual pressure [m]"""
    EmitterCoeff = "EmitterCoeff"
    """Emitter coefficient"""
    FlushingDemand = "FlushingDemand"
    """Flushing demand [m^3/s]"""
    StartHour = "StartHour"
    """Start hour [h]"""
    IdleInterval = "IdleInterval"
    """Idle interval [h]"""
    SaftyFactor = "SaftyFactor"
    """Safty factor"""
    MaxFlushTimeSpan = "MaxFlushTimeSpan"
    """Max flush time span [min]"""
    StartNodeNo = "StartNodeNo"
    """Start node no"""
    StartNodeID = "StartNodeID"
    """Start node id"""
    StartNodeList = "StartNodeList"
    """Start node list"""
    HydrantLayer = "HydrantLayer"
    """Hydrant layer"""
    ValveLayer = "ValveLayer"
    """Valve layer"""
    IdentifyClosedPipeNo = "IdentifyClosedPipeNo"
    """Identify closed pipe no"""
    UseToleranceNo = "UseToleranceNo"
    """Use tolerance no"""
    Tolerance = "Tolerance"
    """Tolerance"""
    ClosedPipes = "ClosedPipes"
    """Closed pipes"""
    Description = "Description"
    """Description"""

class mw_FlushingTable(BaseTable):
    """Table for mw_Flushing (Flushing analysis)."""
    
    @property
    def columns(self) -> mw_FlushingTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_FlushingTableColumns(self)
        return self._columns