from mikeplus.tables.base_node_table import BaseNodeTable
from mikeplus.tables.base_node_table import BaseColumns

class mw_JunctionTableColumns(BaseColumns):
    """Column names for mw_Junction (Junctions)."""
    MUID = "MUID"
    """ID"""
    GeomX = "GeomX"
    """X [m]"""
    GeomY = "GeomY"
    """Y [m]"""
    TypeNo = "TypeNo"
    """Node type"""
    Elev = "Elev"
    """Elevation [m]"""
    EstHeight = "EstHeight"
    """Estate height [m]"""
    Z = "Z"
    """Surface elevation [m]"""
    DemCoeff = "DemCoeff"
    """Demand coefficient"""
    MinPre = "MinPre"
    """Minimum pressure [m]"""
    ZoneID = "ZoneID"
    """Zone ID"""
    Enabled = "Enabled"
    """Is active"""
    Em_FlowCoeff = "Em_FlowCoeff"
    """Flow coefficient [l/s/m^(1/2)]"""
    Init_Quality_Concentration = "Init_Quality_Concentration"
    """Chemical concentration [mg/l]"""
    Init_Quality_Percentage = "Init_Quality_Percentage"
    """Source percentage [%]"""
    Init_Quality_Hour = "Init_Quality_Hour"
    """Water age [h]"""
    AV_Diameter = "AV_Diameter"
    """Valve diameter [mm]"""
    AV_Kapa = "AV_Kapa"
    """Polytropic expansion"""
    AV_ValveCurveID = "AV_ValveCurveID"
    """Dual-acting valve curve"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    Description = "Description"
    """Description"""
    Note = "Note"
    """Note"""
    FFPREREQ = "FFPREREQ"
    """FFPREREQ"""
    FFFLOREQ = "FFFLOREQ"
    """FFFLOREQ"""
    gF = "gF"
    """gF"""
    smF = "smF"
    """smF"""

class mw_JunctionTable(BaseNodeTable):
    """Table for mw_Junction (Junctions)."""
    
    @property
    def columns(self) -> mw_JunctionTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_JunctionTableColumns(self)
        return self._columns