from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mw_PipeTableColumns(BaseColumns):
    """Column names for mw_Pipe (Pipes)."""
    MUID = "MUID"
    """ID"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    L = "L"
    """Length [m]"""
    Diameter = "Diameter"
    """Diameter [mm]"""
    Thickness = "Thickness"
    """Wall thickness [mm]"""
    Inner_Diameter = "Inner_Diameter"
    """Inner diameter [mm]"""
    GeometricLength = "GeometricLength"
    """Geometric length [m]"""
    StatusNo = "StatusNo"
    """Initial status"""
    ZoneID = "ZoneID"
    """Zone ID"""
    Enabled = "Enabled"
    """Is active"""
    RCoeff = "RCoeff"
    """Roughness"""
    LCoeff = "LCoeff"
    """Loss coefficient"""
    PN = "PN"
    """Pressure nominal [m]"""
    Material = "Material"
    """Material"""
    CDate = "CDate"
    """Construction year"""
    Coeff1 = "Coeff1"
    """Demand Coeff. 1"""
    Coeff2 = "Coeff2"
    """Demand Coeff. 2"""
    Coeff3 = "Coeff3"
    """Demand Coeff. 3"""
    Coeff4 = "Coeff4"
    """Demand Coeff. 4"""
    Bulk_Coeff = "Bulk_Coeff"
    """Bulk coefficient [/d]"""
    Wall_Coeff = "Wall_Coeff"
<<<<<<< HEAD
    """Wall coefficient [/d]"""
=======
    LimitingPotential = "LimitingPotential"
>>>>>>> bc29183 (Update auto generated tables for MIKE+ 2026)
    WaveSpeed = "WaveSpeed"
    """Wave speed [m/s]"""
    CVTimeOpen = "CVTimeOpen"
    """Check valve time to open [sec]"""
    CVTimeClose = "CVTimeClose"
    """Check valve time to close [sec]"""
    CVPressure = "CVPressure"
    """Check valve cracking pressure [m]"""
    CVVelocity = "CVVelocity"
    """Check valve minimum velocity [m/s]"""
    CVStatOpen = "CVStatOpen"
    """Check valve is regulating"""
    CVReverseQ = "CVReverseQ"
    """Check valve reverse flow [m^3/s]"""
    CVInterval = "CVInterval"
    """Check valve idle interval [sec]"""
    CVCanReopen = "CVCanReopen"
    """Check valve can reopen"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    StreetName = "StreetName"
    """Street name"""
    Description = "Description"
    """Description"""
    Note = "Note"
    """Note"""
    GroupID = "GroupID"
    """GroupID"""
    PMapZone = "PMapZone"
    """PMapZone"""
    UserLno = "UserLno"
    """UserLno"""

class mw_PipeTable(BaseGeometryTable):
    """Table for mw_Pipe (Pipes)."""
    
    @property
    def columns(self) -> mw_PipeTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_PipeTableColumns(self)
        return self._columns