from mikeplus.tables.base_table import BaseTable
from mikeplus.tables.base_table import BaseColumns

class mw_ProjectTableColumns(BaseColumns):
    """Column names for mw_Project (Simulation setup)."""
    MUID = "MUID"
    """ID"""
    Sqn = "Sqn"
    """Sqn"""
    IncludeToBatchNo = "IncludeToBatchNo"
    """Include to batch"""
    ScenarioID = "ScenarioID"
    """Scenario ID"""
    ActiveProject = "ActiveProject"
    """Active simulation"""
    SimType = "SimType"
    """Simulation type"""
    QualityNo = "QualityNo"
    """Quality No"""
    MsxRunTypeNo = "MsxRunTypeNo"
    """Water quality simulation type"""
    MsxHydFile = "MsxHydFile"
    """Hydraulics file"""
    StartTime = "StartTime"
    """Time start"""
    EndTime = "EndTime"
    """End time"""
    Hydr_Timestep = "Hydr_Timestep"
    """Hydraulic time step [sec]"""
    Pattern_Timestep = "Pattern_Timestep"
    """Pattern time step [sec]"""
    Qual_Timestep = "Qual_Timestep"
    """Quality time step [sec]"""
    Gravity = "Gravity"
    """Specific gravity"""
    Viscosity = "Viscosity"
    """Viscosity"""
    Diffusivity = "Diffusivity"
    """Molecular diffusivity"""
    Emitter = "Emitter"
    """Emitter exponent"""
    Trials = "Trials"
    """Max num. of trials"""
    UnbalancedNo = "UnbalancedNo"
    """Unbalanced system"""
    Accuracy = "Accuracy"
    """Accuracy"""
    CheckFreq = "CheckFreq"
    """Check frequency"""
    Tolerance = "Tolerance"
    """WQ tolerance [mg/l]"""
    MaxCheck = "MaxCheck"
    """Max check"""
    Segments = "Segments"
    """Max num. of segments"""
    DampLimit = "DampLimit"
    """Damp limit"""
    MaxHeadError = "MaxHeadError"
    """Max. Head Error [m]"""
    MaxFlowChange = "MaxFlowChange"
    """Max. Flow Change [m^3/s]"""
    ContinueTimeStepNo = "ContinueTimeStepNo"
    """Continue time step"""
    PatternID = "PatternID"
    """Pattern ID"""
    UseOrderWNo = "UseOrderWNo"
    """Pipe wall reaction order"""
    UseOrderBNo = "UseOrderBNo"
    """Bulk reaction order"""
    UseLimitPNo = "UseLimitPNo"
    """Limiting potential"""
    UseCorrCNo = "UseCorrCNo"
    """Roughness correlation"""
    WallCoeff = "WallCoeff"
    """Pipe wall reaction rate coefficient"""
    BulkCoeff = "BulkCoeff"
    """Bulk reaction rate coefficient"""
    OrderWall = "OrderWall"
    """Order wall"""
    OrderBulk = "OrderBulk"
    """Order bulk"""
    LimitPot = "LimitPot"
    """Limit plot"""
    CorrCoeff = "CorrCoeff"
    """Correlation coefficient"""
    NewBulkCoeff = "NewBulkCoeff"
    """New bulk coefficient"""
    NewBulkCoeffHRS = "NewBulkCoeffHRS"
    """Time of new bulk coefficient"""
    CCT_Materials = "CCT_Materials"
    """Material"""
    HDOutputNo = "HDOutputNo"
    """HD output No"""
    HDFolderPath = "HDFolderPath"
    """HD folder path"""
    HDFileName = "HDFileName"
    """HD file name"""
    SaveRawResultsNo = "SaveRawResultsNo"
    """Report raw results"""
    MsxSaveHydrolicsNo = "MsxSaveHydrolicsNo"
    """Save hydraulics file"""
    Report_Timestep = "Report_Timestep"
    """Report time step [sec]"""
    Report_StartTime = "Report_StartTime"
    """Report start time"""
    StatisticsNo = "StatisticsNo"
    """Statistics"""
    Theta = "Theta"
    """Theta [()]"""
    Alpha = "Alpha"
    """Alpha [()]"""
    G = "G"
    """Gravity acceleration [m/s^2]"""
    Hatm = "Hatm"
    """Atmospheric pressure [m]"""
    Hvap = "Hvap"
    """Vapour cavity pressure [m]"""
    Temperature = "Temperature"
    """Temperature [deg C]"""
    UnsteadyFlowFrictionNo = "UnsteadyFlowFrictionNo"
    """Add unsteady flow friction"""
    Description = "Description"
    """Description"""

class mw_ProjectTable(BaseTable):
    """Table for mw_Project (Simulation setup)."""
    
    @property
    def columns(self) -> mw_ProjectTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_ProjectTableColumns(self)
        return self._columns