from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mw_PumpTableColumns(BaseColumns):
    """Column names for mw_Pump (Pumps)."""
    MUID = "MUID"
    """ID"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    TypeNo = "TypeNo"
    """Type"""
    CurveTypeNo = "CurveTypeNo"
    """Curve type"""
    QHCurveID = "QHCurveID"
    """QH curve"""
    Setting = "Setting"
    """Relative speed"""
    PatternID = "PatternID"
    """Pattern"""
    Elev = "Elev"
    """Elevation [m]"""
    ZoneID = "ZoneID"
    """Zone ID"""
    StatusNo = "StatusNo"
    """Closed"""
    Enabled = "Enabled"
    """Is active"""
    Par2 = "Par2"
    """Design head [m]"""
    Par3 = "Par3"
    """Design flow [m^3/s]"""
    Par1 = "Par1"
    """Shutoff head [m]"""
    Par4 = "Par4"
    """High end head [m]"""
    Par5 = "Par5"
    """High end flow [m^3/s]"""
    Par6 = "Par6"
    """Constant power [W]"""
    VSD_TypeNo = "VSD_TypeNo"
    """Control type"""
    VSD_Node = "VSD_Node"
    """Control node"""
    VSD_Link = "VSD_Link"
    """Control link"""
    VSD_CtrlLevelTypeNo = "VSD_CtrlLevelTypeNo"
    """Control item"""
    VSD_Pressure = "VSD_Pressure"
    """Control pressure [m]"""
    VSD_HGL = "VSD_HGL"
    """Control HGL [m]"""
    VSD_MinSpeed = "VSD_MinSpeed"
    """Minimum speed"""
    VSD_MaxSpeed = "VSD_MaxSpeed"
    """Maximum speed"""
    VSD_CtrlFlow = "VSD_CtrlFlow"
    """Control flow [m^3/s]"""
    VSD_Curve = "VSD_Curve"
    """VSD curve"""
    EPrice = "EPrice"
    """Energy price"""
    EPatternID = "EPatternID"
    """Energy price pattern"""
    EfCurveID = "EfCurveID"
    """Effective curve"""
    P_ScheduleNo = "P_ScheduleNo"
    """Operation type"""
    P_ScheduleID = "P_ScheduleID"
    """Operation schedule"""
    P_Speed = "P_Speed"
    """Rotational pump speed [rpm]"""
    P_IW = "P_IW"
    """Moment of inertia [kg*m^2]"""
    P_PTorqueID = "P_PTorqueID"
    """Pump torque"""
    C_MTorqueID = "C_MTorqueID"
    """Motor torque"""
    P_TTripoff = "P_TTripoff"
    """Pump tripoff time [sec]"""
    p_TStartup = "p_TStartup"
    """Pump startup time [sec]"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    StreetName = "StreetName"
    """Street name"""
    Description = "Description"
    """Description"""
    Note = "Note"
    """Note"""
    CDate = "CDate"
    """Date"""

class mw_PumpTable(BaseGeometryTable):
    """Table for mw_Pump (Pumps)."""
    
    @property
    def columns(self) -> mw_PumpTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_PumpTableColumns(self)
        return self._columns