from mikeplus.tables.base_geometry_table import BaseGeometryTable
from mikeplus.tables.base_geometry_table import BaseColumns

class mw_ValveTableColumns(BaseColumns):
    """Column names for mw_Valve (Valves)."""
    MUID = "MUID"
    """ID"""
    FromNodeID = "FromNodeID"
    """From node"""
    ToNodeID = "ToNodeID"
    """To node"""
    TypeNo = "TypeNo"
    """Valve type"""
    SettingNo = "SettingNo"
    """Setting type"""
    Setting = "Setting"
    """Setting"""
    Diameter = "Diameter"
    """Diameter [mm]"""
    LossCoeff = "LossCoeff"
    """Loss coefficient"""
    StatusNo = "StatusNo"
    """Fixed status"""
    HLCurveID = "HLCurveID"
    """Curve"""
    Elev = "Elev"
    """Elevation [m]"""
    ZoneID = "ZoneID"
    """Zone ID"""
    Enabled = "Enabled"
    """Is active"""
    DataSource = "DataSource"
    """Data source"""
    AssetName = "AssetName"
    """Asset ID"""
    Element_S = "Element_S"
    """Status"""
    StreetName = "StreetName"
    """Street name"""
    Description = "Description"
    """Description"""
    Note = "Note"
    """Note"""
    CDate = "CDate"
    """CDate"""
    LCoeff = "LCoeff"
    """LCoeff"""
    OperCurveID = "OperCurveID"
    """Operation schedule"""
    ValveCurveID = "ValveCurveID"
    """Valve characteristics"""
    FullStrokeTime = "FullStrokeTime"
    """Full stroke time [sec]"""
    PressureOverride = "PressureOverride"
    """Pressure Override"""
    PressureOverrideLimit = "PressureOverrideLimit"
    """Pressure Override Limit [m]"""
    LevelControlEnabled = "LevelControlEnabled"
    """Level control"""
    TankID = "TankID"
    """TankID"""
    LevelOpen = "LevelOpen"
    """Level open [m]"""
    LevelClose = "LevelClose"
    """Level close [m]"""

class mw_ValveTable(BaseGeometryTable):
    """Table for mw_Valve (Valves)."""
    
    @property
    def columns(self) -> mw_ValveTableColumns:
        """Get the columns for the table."""
        if self._columns is None:
            self._columns = mw_ValveTableColumns(self)
        return self._columns