name: Full Test

on:
  workflow_dispatch:
  
  #push:
  # branches: [ "main" ]
  # pull_request:
  # branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Checkout branch with MIKE+ dependency
        uses: actions/checkout@v3
        with:
          lfs: true
          ref: cicd_dependencies

      - name: Unzip MIKE+ dependency
        run: |
          7z x "2025_0.7z" -p${{ secrets.MIKE_2024_0_7Z }} # Use secrets.MIKE_2024_0_7Z regardless of version

      - name: Install MIKE+ dependency
        run: |
            ./install.ps1 2025

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install mikepluspy
        run: just setup dev,test

      - name: Lint
        run: just lint

      - name: Test with pytest
        run: just test-unlicensed -v
