name: Full test

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Download and install MIKE+ 2024 demo
      run: |
        curl -L -o mike.7z https://raw.githubusercontent.com/DHI/mikepluspy/cicd_dependencies/2024_0.7z
        mkdir -p "C:\Program Files (x86)\DHI\2024"
        7z x "2024_0.7z" -o"C:\Program Files (x86)\DHI\MIKE+\2024" -p${{ secrets.MIKE_2024_0_7Z }}
    - name: Install mikepluspy
      run: |
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest
