name: Full Test (self-hosted)

on:
  workflow_dispatch:
  
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1 # Fail fast if there are any linting errors

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install shapely

      - name: Install mikepluspy
        run: |
          python -m pip install -e .[test]

      - name: Test with pytest
        run: |
          pytest -v
