name: Full Test (self-hosted)

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "."  # Adjust the source directory as needed

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
      - name: Run mypy
        run: |
          mypy mikeplus/

  test:
    runs-on: self-hosted
    needs: [lint, types]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up UV and Python ${{ matrix.python-version }}
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/setup.py
            **/pyproject.toml

      - name: Install project dependencies and test requirements
        run: |
          uv pip install -e .[test]

      - name: Test with pytest
        run: |
          uv run pytest -v
